'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Building2,Plus,Users,ClipboardList,Save,RotateCcw,Download,Settings2,Trash2,BookOpen} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {SUBJECTS,GRADES,emptySnapshot,total,type Snapshot,type Student,type Score} from '@/lib/score';
type DialogKind='campus'|'student'|'test'|'average'|null;
const blank=()=>Object.fromEntries(SUBJECTS.map(s=>[s,{score:'',dev:''}])) as Record<string,Score>;
function Picker({label,value,onChange,items,placeholder='選択してください',disabled=false}:{label:string;value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];placeholder?:string;disabled?:boolean}){return <div className="field"><label>{label}</label><Select value={value||undefined} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select></div>}
function Fields({children}:{children:React.ReactNode}){return <div className="fields">{children}</div>}
function FormInput({name,label,defaultValue='',type='text',required=true,...props}:{name:string;label:string;defaultValue?:string|number;type?:string;required?:boolean;min?:number;max?:number;maxLength?:number;list?:string}){return <div className="field"><label htmlFor={'form-'+name}>{label}</label><Input id={'form-'+name} name={name} defaultValue={defaultValue} type={type} step={type==='number'?'any':undefined} required={required} maxLength={80} {...props}/></div>}
function downloadCSV(filename:string,rows:(string|number|null)[][]){const escape=(v:string|number|null)=>'"'+String(v??'').replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"',blob=new Blob(['\ufeff'+rows.map(r=>r.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function ScoreApp(){
 const [data,setData]=useState<Snapshot>(emptySnapshot),[campusId,setCampusId]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[unauthorized,setUnauthorized]=useState(false),[tab,setTab]=useState('input');
 const [dialog,setDialog]=useState<DialogKind>(null),[editStudent,setEditStudent]=useState<Student|null>(null),[year,setYear]=useState(String(new Date().getFullYear())),[testId,setTestId]=useState(''),[grade,setGrade]=useState(''),[studentId,setStudentId]=useState(''),[values,setValues]=useState(blank),[rank,setRank]=useState(''),[collect,setCollect]=useState('未回収'),[memo,setMemo]=useState(''),[dirty,setDirty]=useState(false),[confirmDelete,setConfirmDelete]=useState(false),[search,setSearch]=useState(''),[onlyUnsaved,setOnlyUnsaved]=useState(false),[reload,setReload]=useState(0);
 const request=useRef(0);
 const campus=data.campuses.find(c=>c.id===campusId),student=data.students.find(s=>s.id===studentId),record=data.records.find(r=>r.student_id===studentId&&r.test_id===testId),average=data.averages.find(a=>a.test_id===testId&&a.grade===student?.grade&&a.school===student?.school),currentTest=data.tests.find(t=>t.id===testId);
 const years=[...new Set(data.tests.map(t=>String(t.year)))].sort().reverse(),tests=data.tests.filter(t=>String(t.year)===year),students=data.students.filter(s=>s.status==='在籍'&&s.start_year<=Number(year)&&(!grade||s.grade===grade)),schools=[...new Set(data.students.map(s=>s.school).concat(data.averages.map(a=>a.school)))].sort(),registeredGrades=GRADES.filter(g=>data.students.some(s=>s.grade===g&&s.status==='在籍'));
 async function api(action:string,payload:Record<string,unknown>={}){const r=await fetch('/api/score',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,campusId,...payload})});const result=await r.json() as {error?:string;ok?:boolean;id?:string};if(!r.ok)throw Error(result.error||'保存できませんでした');return result;}
 useEffect(()=>{let cancelled=false;const controller=new AbortController(),n=++request.current;setLoading(true);setError('');fetch('/api/score'+(campusId?'?campus='+encodeURIComponent(campusId):''),{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json() as Snapshot & {error?:string};if(!r.ok){setUnauthorized(r.status===401);throw Error(d.error||'読み込みできませんでした')}if(!cancelled&&n===request.current){setUnauthorized(false);setData(d);if(!campusId&&d.campuses.length)setCampusId(d.campuses[0].id);}}).catch(e=>{if(!cancelled&&e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true;controller.abort()};},[campusId,reload]);
 useEffect(()=>{if(years.length&&!years.includes(year))setYear(years[0]);if(testId&&!data.tests.some(t=>t.id===testId))setTestId('');},[data]);
 useEffect(()=>{setValues(record?.scores||blank());setRank(record?.rank==null?'':String(record.rank));setCollect(record?.collect||'未回収');setMemo(record?.memo||'');setDirty(false)},[studentId,testId,record?.revision,campusId]);
 useEffect(()=>{const listener=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',listener);return()=>window.removeEventListener('beforeunload',listener)},[dirty]);
 function canLeave(){return !dirty||window.confirm('入力途中の内容は保存されません。移動しますか？')}
 function changeCampus(id:string){if(busy||!canLeave())return;setData(prev=>({...emptySnapshot,campuses:prev.campuses}));setCampusId(id);setStudentId('');setTestId('');setGrade('');setMessage('');setDirty(false);setSearch('');}
 async function mutate(action:string,payload:Record<string,unknown>,success:string){if(busy)return;setBusy(true);setError('');setMessage('');try{const result=await api(action,payload);setMessage(success);setReload(n=>n+1);return result}catch(e){setError(e instanceof Error?e.message:'保存できませんでした');return null}finally{setBusy(false)}}
 async function saveRecord(){if(!student||!currentTest){setError('テスト・学年・生徒を選択してください');return}const result=await mutate('saveRecord',{studentId,testId,scores:values,rank,collect,memo,revision:record?.revision||0},'成績を保存しました');if(result)setDirty(false)}
 async function createCampus(name:string){const result=await mutate('createCampus',{name},'校舎を登録しました');if(result){setDialog(null);setCampusId(result.id!);setTestId('');setStudentId('');setGrade('');setDirty(false)}}
 async function submitForm(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget),d=Object.fromEntries(form.entries());if(dialog==='campus'){await createCampus(String(d.name));return}let action='',payload:Record<string,unknown>={};if(dialog==='student'){action='saveStudent';payload={...d,id:editStudent?.id}}if(dialog==='test'){action='saveTest';payload=d}if(dialog==='average'){action='saveAverage';payload={...d,values:Object.fromEntries(SUBJECTS.map(s=>[s,d[s]]))}}if(!action)return;const result=await mutate(action,payload,'登録内容を保存しました');if(result){setDialog(null);setEditStudent(null)}}
 const filtered=data.students.filter(s=>(s.name+s.code+s.school).includes(search));
 function exportHistory(){const rows=data.records.map(r=>{const st=data.students.find(s=>s.id===r.student_id),t=data.tests.find(t=>t.id===r.test_id);return [campus?.name||'',t?.year||'',t?.name||'',r.grade,st?.code||'',st?.name||'',r.school,...SUBJECTS.flatMap(s=>[r.scores[s]?.score||'',r.averages[s]||'',r.scores[s]?.dev||'']),total(r.scores),r.rank,r.collect,r.memo,r.updated_at]});downloadCSV('ScoreInput_成績履歴.csv',[['校舎','年度','テスト','学年','生徒番号','生徒名','学校',...SUBJECTS.flatMap(s=>[s,s+' 学校平均',s+' 偏差値']),'5科合計','順位','回収','メモ','保存日時'],...rows])}
 useEffect(()=>{type Context={registerTool:(t:unknown,o:{signal:AbortSignal})=>unknown};const context=(document as Document&{modelContext?:Context}).modelContext;if(!context)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'score_input_read_current_campus',title:'校舎の登録状況を読む',description:'表示中の校舎名と生徒・テスト・保存済み成績の件数を返す。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({campus:campus?.name||null,students:data.students.length,tests:data.tests.length,records:data.records.length})},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort()},[campus,data]);
 const savedCount=students.filter(s=>data.records.some(r=>r.student_id===s.id&&r.test_id===testId)).length;
 return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-icon"><ClipboardList size={24}/></span><div><b>Score Input</b><span>校舎共通版</span></div></div><div className="campus-control">{campus&&<Picker label="校舎" value={campusId} onChange={changeCampus} items={data.campuses.map(c=>({value:c.id,label:c.name}))} disabled={busy||loading}/>}<Button variant="outline" onClick={()=>{if(canLeave())setDialog('campus')}} disabled={busy||loading||unauthorized}><Plus size={16}/>{campus?'校舎を追加':'校舎を登録'}</Button></div></header>
 <main className="workspace">{error&&<div className="notice error" role="alert">{error}{unauthorized&&<a href="/cdn-cgi/access/login" target="_top">ログインする</a>}<Button variant="outline" size="sm" onClick={()=>setReload(n=>n+1)}>再読み込み</Button></div>}{message&&<div className="notice success" role="status">{message}</div>}
 {!campus?<section className="onboarding"><div className="setup-icon"><Building2 size={34}/></div><p className="eyebrow">はじめての設定</p><h1>あなたの校舎で、使い始める。</h1><p>校舎名を入力すると、専用の成績管理を始められます。</p><form onSubmit={e=>{e.preventDefault();createCampus(String(new FormData(e.currentTarget).get('name')||''))}}><label htmlFor="first-campus">校舎名</label><Input id="first-campus" name="name" placeholder="例：○○塾 △△校" maxLength={80} required disabled={busy||loading||unauthorized}/><Button disabled={busy||loading||unauthorized} type="submit">{loading?'読み込み中…':busy?'登録中…':'この校舎で始める'}</Button></form><div className="setup-note"><span>1　校舎名を登録</span><span>2　生徒とテストを追加</span><span>3　成績を入力</span></div></section>:<>
 <div className="page-heading"><div><p className="eyebrow">{campus.name}</p><h1>テスト成績を、まとめて管理。</h1></div><div className="summary"><b>{data.students.filter(s=>s.status==='在籍').length}</b><span>在籍生徒</span><b>{data.tests.length}</b><span>登録テスト</span></div></div>
 <Tabs value={tab} onValueChange={v=>{if(canLeave()){setTab(v);setDirty(false)}}}><TabsList className="main-tabs"><TabsTrigger value="input"><ClipboardList/>成績入力</TabsTrigger><TabsTrigger value="history"><BookOpen/>成績一覧</TabsTrigger><TabsTrigger value="students"><Users/>生徒マスター</TabsTrigger><TabsTrigger value="tests">テスト設定</TabsTrigger><TabsTrigger value="averages">学校平均</TabsTrigger><TabsTrigger value="settings"><Settings2/>設定</TabsTrigger></TabsList>
 <TabsContent value="input"><section className="panel"><div className="section-heading"><h2>入力する生徒を選ぶ</h2>{record&&<span className="badge">保存済み</span>}</div><Fields><Picker label="年度" value={year} onChange={v=>{if(canLeave()){setYear(v);setTestId('');setStudentId('')}}} items={years.map(y=>({value:y,label:y+'年度'}))} disabled={busy||loading}/><Picker label="テスト" value={testId} onChange={v=>{if(canLeave()){setTestId(v);setDirty(false)}}} items={tests.map(t=>({value:t.id,label:t.name}))} disabled={busy||loading}/><Picker label="学年" value={grade} onChange={v=>{if(canLeave()){setGrade(v);setStudentId('');setDirty(false)}}} items={registeredGrades.map(g=>({value:g,label:g}))} disabled={busy||loading}/><Picker label="生徒" value={studentId} onChange={v=>{if(canLeave()){setStudentId(v);setDirty(false)}}} items={students.filter(s=>grade&&s.grade===grade).map(s=>({value:s.id,label:s.name+'（'+s.code+'）'}))} disabled={!grade||busy||loading}/></Fields>{student?<div className="student-strip"><strong>{student.name}</strong><span>{student.grade}　{student.school}</span><span>{record?'最終保存 '+new Date(record.updated_at).toLocaleString('ja-JP'):'新規入力'}</span></div>:<p className="helper">{!data.students.length?'生徒マスターから生徒を追加してください。':!data.tests.length?'テスト設定から年度とテストを登録してください。':'年度・テスト・学年・生徒の順に選択してください。'}</p>}</section>
 <div className="input-layout"><section className="panel score-panel"><div className="section-heading"><h2>5教科の成績</h2><span className="helper">学校平均は自動反映</span></div><div className="score-table"><div className="score-head"><span>教科</span><span>本人点</span><span>学校平均</span><span>偏差値</span></div>{SUBJECTS.map((s,i)=><div className="score-row" key={s}><div className={'subject-name subject-'+i}>{s}</div><Input aria-label={s+' 本人点'} type="number" min={0} max={100} step="any" placeholder="—" value={values[s]?.score||''} disabled={!student||!testId||busy||loading} onChange={e=>{setValues(v=>({...v,[s]:{...v[s],score:e.target.value}}));setDirty(true)}}/><div className="average-value">{average?.values[s]||'—'}</div><Input aria-label={s+' 偏差値'} type="number" min={0} max={100} step="any" placeholder="—" value={values[s]?.dev||''} disabled={!student||!testId||busy||loading} onChange={e=>{setValues(v=>({...v,[s]:{...v[s],dev:e.target.value}}));setDirty(true)}}/></div>)}</div><div className="total-strip"><span>5科合計 <small>入力済み科目の合計</small></span><strong>{total(values)??'—'}<small>点</small></strong></div></section>
 <section className="panel notes-panel"><h2>回収・メモ</h2><div className="field"><label htmlFor="rank">順位</label><Input id="rank" type="number" min={1} step={1} value={rank} onChange={e=>{setRank(e.target.value);setDirty(true)}} disabled={!student||busy||loading} placeholder="例：12"/></div><Picker label="回収状況" value={collect} onChange={v=>{setCollect(v);setDirty(true)}} items={['未回収','回収済'].map(v=>({value:v,label:v}))} disabled={!student||busy||loading}/><div className="field"><label htmlFor="memo">メモ</label><Textarea id="memo" value={memo} onChange={e=>{setMemo(e.target.value);setDirty(true)}} maxLength={2000} rows={5} disabled={!student||busy||loading} placeholder="面談や次のテストに向けたメモ"/></div></section></div>
 <div className="save-bar"><span>{dirty?'未保存の入力があります':record?'保存済みの成績を表示中':'入力後に保存してください'}</span><div><Button variant="outline" disabled={busy||loading||!record} onClick={()=>setConfirmDelete(true)}><Trash2 size={16}/>削除</Button><Button variant="outline" disabled={busy||loading} onClick={()=>{if(canLeave()){setDirty(false);setStudentId('')}}}><RotateCcw size={16}/>選び直す</Button><Button disabled={busy||loading||!student||!testId} onClick={saveRecord}><Save size={16}/>{busy?'保存中…':'成績を保存'}</Button></div></div></TabsContent>
 <TabsContent value="history"><section className="panel"><div className="section-heading"><div><h2>成績一覧</h2><p className="helper">{testId?`${savedCount} / ${students.length} 名 保存済み`:'年度とテストを選択してください'}</p></div><Button variant="outline" onClick={exportHistory} disabled={!data.records.length}><Download size={16}/>履歴CSV</Button></div><Fields><Picker label="年度" value={year} onChange={v=>{setYear(v);setTestId('')}} items={years.map(y=>({value:y,label:y+'年度'}))}/><Picker label="テスト" value={testId} onChange={setTestId} items={tests.map(t=>({value:t.id,label:t.name}))}/><Picker label="学年" value={grade||'all'} onChange={v=>setGrade(v==='all'?'':v)} items={[{value:'all',label:'すべて'},...registeredGrades.map(g=>({value:g,label:g}))]}/><Picker label="表示する生徒" value={onlyUnsaved?'unsaved':'all'} onChange={v=>setOnlyUnsaved(v==='unsaved')} items={[{value:'all',label:'すべて'},{value:'unsaved',label:'未保存のみ'}]}/></Fields><Table><TableHeader><TableRow><TableHead>生徒</TableHead>{SUBJECTS.map(s=><TableHead key={s}>{s}</TableHead>)}<TableHead>合計</TableHead><TableHead>順位</TableHead><TableHead>保存状況</TableHead><TableHead/></TableRow></TableHeader><TableBody>{testId&&students.filter(s=>!onlyUnsaved||!data.records.some(r=>r.student_id===s.id&&r.test_id===testId)).map(s=>{const r=data.records.find(r=>r.student_id===s.id&&r.test_id===testId);return <TableRow key={s.id}><TableCell><b>{s.name}</b><small>{s.grade}・{s.school}</small></TableCell>{SUBJECTS.map(sub=><TableCell key={sub}>{r?.scores[sub]?.score||'—'}</TableCell>)}<TableCell>{r?total(r.scores)??'—':'—'}</TableCell><TableCell>{r?.rank||'—'}</TableCell><TableCell>{r?'保存済み':'未保存'}</TableCell><TableCell><Button size="sm" variant="outline" onClick={()=>{setGrade(s.grade);setStudentId(s.id);setTab('input')}}>入力</Button></TableCell></TableRow>})}</TableBody></Table>{!testId&&<div className="empty">テストを選ぶと、生徒ごとの点数が表示されます。</div>}</section></TabsContent>
 <TabsContent value="students"><section className="panel"><div className="section-heading"><div><h2>生徒マスター</h2><p className="helper">新規入塾・退塾・進級はここで更新します。</p></div><Button onClick={()=>{setEditStudent(null);setDialog('student')}}><Plus size={16}/>生徒を追加</Button></div><Input value={search} onChange={e=>setSearch(e.target.value)} aria-label="生徒を検索" placeholder="名前・生徒番号・学校で検索" className="search-input"/><Table><TableHeader><TableRow><TableHead>生徒番号</TableHead><TableHead>氏名</TableHead><TableHead>学年</TableHead><TableHead>学校</TableHead><TableHead>在籍</TableHead><TableHead/></TableRow></TableHeader><TableBody>{filtered.map(s=><TableRow key={s.id}><TableCell>{s.code}</TableCell><TableCell><b>{s.name}</b></TableCell><TableCell>{s.grade}</TableCell><TableCell>{s.school}</TableCell><TableCell>{s.status}</TableCell><TableCell><Button variant="outline" size="sm" onClick={()=>{setEditStudent(s);setDialog('student')}}>編集</Button></TableCell></TableRow>)}</TableBody></Table>{!filtered.length&&<div className="empty">{data.students.length?'該当する生徒がいません。':'生徒を追加して、成績入力を始めましょう。'}</div>}</section></TabsContent>
 <TabsContent value="tests"><section className="panel"><div className="section-heading"><div><h2>テスト設定</h2><p className="helper">年度とテスト名は校舎ごとに自由に登録できます。</p></div><Button onClick={()=>setDialog('test')}><Plus size={16}/>テストを追加</Button></div><Table><TableHeader><TableRow><TableHead>年度</TableHead><TableHead>テスト名</TableHead><TableHead>保存件数</TableHead></TableRow></TableHeader><TableBody>{data.tests.map(t=><TableRow key={t.id}><TableCell>{t.year}年度</TableCell><TableCell><b>{t.name}</b></TableCell><TableCell>{data.records.filter(r=>r.test_id===t.id).length}件</TableCell></TableRow>)}</TableBody></Table>{!data.tests.length&&<div className="empty">例：2026年度「2学期中間」「第1回模試」など。</div>}</section></TabsContent>
 <TabsContent value="averages"><section className="panel"><div className="section-heading"><div><h2>学校平均マスター</h2><p className="helper">テスト・学年・学校が一致する生徒の入力画面に反映します。</p></div><Button onClick={()=>setDialog('average')} disabled={!data.tests.length}><Plus size={16}/>平均を登録・更新</Button></div><Table><TableHeader><TableRow><TableHead>テスト</TableHead><TableHead>学校・学年</TableHead>{SUBJECTS.map(s=><TableHead key={s}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{data.averages.map(a=><TableRow key={a.id}><TableCell>{data.tests.find(t=>t.id===a.test_id)?.year}年度<small>{data.tests.find(t=>t.id===a.test_id)?.name}</small></TableCell><TableCell>{a.school}<small>{a.grade}</small></TableCell>{SUBJECTS.map(s=><TableCell key={s}>{a.values[s]||'—'}</TableCell>)}</TableRow>)}</TableBody></Table>{!data.averages.length&&<div className="empty">{data.tests.length?'学校平均を登録すると、点数入力時に自動で表示されます。':'先にテスト設定を登録してください。'}</div>}</section></TabsContent>
 <TabsContent value="settings"><section className="panel settings-panel"><h2>校舎の設定</h2><p className="helper">校舎名はあとから変更できます。</p><form onSubmit={e=>{e.preventDefault();mutate('renameCampus',{name:new FormData(e.currentTarget).get('name')},'校舎名を変更しました')}} key={campus.name}><FormInput name="name" label="校舎名" defaultValue={campus.name}/><Button disabled={busy} type="submit">校舎名を保存</Button></form><p className="helper">このアプリのデータは、既存のScore Inputとは別に保存されます。</p></section></TabsContent>
 </Tabs></>}
 </main><footer>Score Input <span>校舎共通版</span></footer>
 <Dialog open={!!dialog} onOpenChange={open=>{if(!open&&!busy){setDialog(null);setEditStudent(null)}}}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{dialog==='campus'?'校舎を登録':dialog==='student'?editStudent?'生徒を編集':'生徒を追加':dialog==='test'?'テストを追加':'学校平均を登録・更新'}</DialogTitle><DialogDescription>{dialog==='campus'?'校舎名を自由に入力してください。':'登録内容は、選択中の校舎に保存されます。'}</DialogDescription></DialogHeader><form key={dialog+(editStudent?.id||'')} onSubmit={submitForm}>{dialog==='campus'&&<FormInput name="name" label="校舎名"/>}{dialog==='student'&&<><Fields><FormInput name="code" label="生徒番号" defaultValue={editStudent?.code}/><FormInput name="name" label="生徒名" defaultValue={editStudent?.name}/></Fields><MasterPicker name="grade" label="学年" items={GRADES} initial={editStudent?.grade||'中1'}/><FormInput name="school" label="学校名" defaultValue={editStudent?.school} list="schools"/><FormInput name="startYear" label="登録年度" type="number" min={2000} max={2099} defaultValue={editStudent?.start_year||new Date().getFullYear()}/><MasterPicker name="status" label="在籍状況" items={['在籍','退塾']} initial={editStudent?.status||'在籍'}/></>}{dialog==='test'&&<><FormInput name="year" label="年度" type="number" min={2000} max={2099} defaultValue={Number(year)}/><FormInput name="name" label="テスト名"/></>}{dialog==='average'&&<AverageForm tests={data.tests} averages={data.averages} schools={schools} initialTest={testId}/>}<datalist id="schools">{schools.map(s=><option key={s} value={s}/>)}</datalist><Button type="submit" disabled={busy}>{busy?'保存中…':'保存する'}</Button>{error&&<p className="form-error" role="alert">{error}</p>}</form></DialogContent></Dialog>
 <AlertDialog open={confirmDelete} onOpenChange={setConfirmDelete}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>この成績を削除しますか？</AlertDialogTitle><AlertDialogDescription>{student?.name}・{currentTest?.name}の保存済み成績が削除されます。元に戻せません。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>キャンセル</AlertDialogCancel><AlertDialogAction onClick={async()=>{const result=await mutate('deleteRecord',{studentId,testId,revision:record?.revision},'成績を削除しました');if(result)setDirty(false)}}>削除する</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}
function MasterPicker({name,label,items,initial}:{name:string;label:string;items:string[];initial:string}){const [v,set]=useState(initial);return <><input type="hidden" name={name} value={v}/><Picker label={label} value={v} onChange={set} items={items.map(i=>({value:i,label:i}))}/></>}
function AverageForm({tests,averages,schools,initialTest}:{tests:Snapshot['tests'];averages:Snapshot['averages'];schools:string[];initialTest:string}){const [tid,setTid]=useState(initialTest||tests[0]?.id||''),[g,setG]=useState('中1'),[school,setSchool]=useState('');const existing=averages.find(a=>a.test_id===tid&&a.grade===g&&a.school===school);return <><input name="testId" type="hidden" value={tid}/><input name="grade" type="hidden" value={g}/><Picker label="テスト" value={tid} onChange={setTid} items={tests.map(t=>({value:t.id,label:t.year+'年度 '+t.name}))}/><Picker label="学年" value={g} onChange={setG} items={GRADES.map(v=>({value:v,label:v}))}/><div className="field"><label htmlFor="average-school">学校名</label><Input id="average-school" name="school" list="schools" value={school} onChange={e=>setSchool(e.target.value)} required maxLength={80}/></div><p className="helper">{existing?'登録済みの平均を表示しています。保存すると更新されます。':'未登録の平均を新しく保存します。'}</p><div className="fields" key={tid+g+school}>{SUBJECTS.map(s=><FormInput key={s} name={s} label={s+'平均'} defaultValue={existing?.values[s]||''} type="number" min={0} max={100} required={false}/>)}</div></>}
