'use strict';
// 接続先は既存の共和校 Score Input と共通。
const ENDPOINT='https://script.google.com/macros/s/AKfycbya7qViVMKVJau3fZ1fgyKF82jkAeQOtMMQSpzC8fqjhRBMgoB9h8cf0nCmWcVL7izntQ/exec';
const SUB=['国語','数学','英語','理科','社会'], $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), present=v=>v!==undefined&&v!==null&&String(v).trim()!=='';
const DEMO=new URLSearchParams(location.search).has('demo'),PREF='kyowa-manager-preferences-v1';
let master={students:[],tests:[],schools:[],capabilities:{}},view='home',mode='',step=0,selection={school:'',grade:'',year:String(new Date().getFullYear()),test:''},rows=[],metric='score',busy=false,run=0,formKind='',extraOpen=new Set(),ready=false;
try{selection={...selection,...JSON.parse(localStorage.getItem(PREF)||'{}')}}catch(_){}
const clone=v=>JSON.parse(JSON.stringify(v));
function emptyRecord(){return {scores:Object.fromEntries(SUB.map(s=>[s,{score:'',avg:'',dev:''}])),rank:'',collect:'未',memo:''}}
function normalize(r){const out=emptyRecord();if(r){SUB.forEach(s=>out.scores[s]={...out.scores[s],...r.scores?.[s]});['rank','collect','memo'].forEach(k=>out[k]=r[k]??out[k])}return out}
function fingerprint(r){return JSON.stringify({scores:SUB.map(s=>[String(r.scores[s].score??''),String(r.scores[s].dev??'')]),rank:String(r.rank??''),collect:r.collect||'未',memo:r.memo||''})}
function dirty(r){return fingerprint(r.draft)!==fingerprint(r.base)}
function count(r){return SUB.filter(s=>present(r.scores[s].score)).length}
function notice(t='',bad=false){$('notice').textContent=DEMO?'体験モード｜架空のデータです。保存先には送信しません。'+(t?' '+t:''):t;$('notice').className=DEMO?'demo':bad?'error':''}
async function request(action,data,write=false){if(DEMO)return demoRequest(action,data,write);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),45000);try{let url=ENDPOINT,options={signal:controller.signal,cache:'no-store'};if(write)options={...options,method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,data})};else{const u=new URL(url);u.searchParams.set('action',action);u.searchParams.set('_request',Date.now()+'-'+Math.random().toString(36).slice(2));if(data)u.searchParams.set('data',JSON.stringify(data));url=u.toString()}const response=await fetch(url,options);if(!response.ok)throw Error('通信エラー（'+response.status+'）');const result=await response.json();if(!result.ok)throw Error(result.message||'処理できませんでした');return result}catch(e){if(e.name==='AbortError')throw Error(write?'保存の応答を確認できませんでした。入力を残しています。再保存する前に保存状況を確認してください。':'読み込みがタイムアウトしました。再試行してください。');throw e}finally{clearTimeout(timer)}}
function remember(){try{localStorage.setItem(PREF,JSON.stringify(selection))}catch(_){}}
function leave(){if(busy)return false;if(rows.some(dirty)&&!confirm('未保存の入力があります。破棄して移動しますか？'))return false;run++;rows=[];extraOpen.clear();return true}
function home(){if(!leave())return;view='home';mode='';render()}
function start(next){if(!ready||!leave())return;if(next==='roster'){rosterSelected.clear();rosterMessages.clear();view='roster';render();return}mode=next;view='choose';step=0;advance();render()}
function optionsFor(n){if(n===0)return ['__all__',...new Set([...master.schools,...master.students.filter(s=>s.status==='在籍').map(s=>s.school)].filter(Boolean))];if(n===1)return [...new Set(master.students.filter(s=>s.status==='在籍'&&(selection.school==='__all__'||(selection.school==='__unset__'?!s.school:s.school===selection.school))).map(s=>s.grade))].sort();if(n===2)return [...new Set(master.tests.map(t=>String(t.year)))].sort().reverse();return master.tests.filter(t=>String(t.year)===selection.year).map(t=>t.name)}
const KEYS=['school','grade','year','test'],STEPS=['中学校','学年','年度','テスト'];
function advance(){while(step<4){const options=optionsFor(step);if(options.length!==1)break;selection[KEYS[step]]=options[0];step++}if(step===4){remember();loadRows()}}
function choose(value){selection[KEYS[step]]=value;step++;advance();render()}
function breadcrumbs(){return [selection.school==='__all__'?'すべての中学校':selection.school==='__unset__'?'学校未設定':selection.school,selection.grade,selection.year+'年度',selection.test].filter(Boolean).map(esc).join(' ／ ')}
function render(){const app=$('app');$('settings').disabled=busy;
if(view==='home'){app.innerHTML=`<h1>共和校 成績管理</h1><p class="muted intro">点数・偏差値の入力と確認</p><div class="home-grid">${[['input','成績を入力','点数・偏差値を登録','＋'],['scores','成績を見る','点数・偏差値・成績履歴','↗'],['status','入力状況を見る','未入力・未回収を確認','✓'],['roster','生徒一覧を見る','名簿の確認・学校の一括登録','≡']].map(([m,title,text,icon])=>`<button class="home-card" data-start="${m}" ${ready?'':'disabled'}><span class="icon">${icon}</span><strong>${title}</strong><small>${text}</small></button>`).join('')}</div><p class="hint">${ready?'名簿・テスト・学校平均は「登録・設定」で管理':'名簿とテストを読み込んでいます。'}</p><button class="quiet" data-action="refresh">名簿を更新</button>`;return}
if(view==='choose'){const opts=optionsFor(step);app.innerHTML=`<button class="back quiet" data-action="back">← 戻る</button><p class="steps">${mode==='input'?'成績を入力':mode==='scores'?'成績を見る':'入力状況を見る'} ／ ${step+1} / 4</p><h1>${STEPS[step]}を選んでください</h1><p class="muted">${KEYS.slice(0,step).map(k=>esc(k==='school'&&selection[k]==='__all__'?'すべての中学校':k==='school'&&selection[k]==='__unset__'?'学校未設定':selection[k])).join(' ／ ')}</p><div class="panel"><div class="choices">${opts.map(v=>`<button class="choice" data-choice="${esc(v)}">${esc(v==='__all__'?'すべての中学校':v)}${selection[KEYS[step]]===v?'<small>前回の選択</small>':''}</button>`).join('')}${step===0&&master.students.some(s=>s.status==='在籍'&&!s.school)?'<button class="choice" data-choice="__unset__">学校未設定<small>まだ学校を登録していない生徒</small></button>':''}</div>${opts.length?'':'<p class="hint">候補がありません。「登録・設定」で追加してください。</p>'}</div>`;return}
if(view==='settings'){app.innerHTML=`<button class="back quiet" data-action="home">← ホーム</button><h1>登録・設定</h1><p class="muted intro">名簿・テスト・学校平均の登録</p>${master.capabilities.manager!==true?'<div class="panel"><b>成績の入力・閲覧は利用できます。</b><p>生徒・中学校・テスト・学校平均の登録機能は、接続先の更新後に利用できます。</p><a href="AppsScript.gs">更新用コード</a> ／ <a href="setup.html">設定手順</a></div>':''}<div class="settings-grid">${[['student','生徒を追加','名前・学年・学校を登録'],['school','中学校を追加','学校名を入力するだけ'],['test','テストを追加','年度とテスト名を登録'],['average','学校平均を入力','5教科の平均点を登録']].map(([k,t,d])=>`<button data-register="${k}">${t}<small>${d}</small></button>`).join('')}</div><div class="panel"><h2>生徒の学校を設定</h2><p class="hint">名簿に生徒の学校を登録します。</p><button data-register="assign">生徒の学校を変更</button></div><button data-action="refresh" class="quiet">最新の名簿・候補を読み込む</button>`;return}
if(view==='loading'){app.innerHTML=`<button class="back quiet" data-action="home">← ホーム</button><h1>成績を読み込み中…</h1><p class="muted">${breadcrumbs()}</p><div class="panel"><p>成績を取得しています。</p></div>`;return}
if(view==='roster'){renderRoster();return}if(view==='list')renderList();}
function renderList(){historyData=null;const records=rows.filter(r=>!r.error),n=records.filter(r=>count(r.draft)===5).length,partial=records.filter(r=>count(r.draft)>0&&count(r.draft)<5).length;
$('app').innerHTML=`<button class="back quiet" data-action="home">← ホーム</button><div class="topline"><div><h1>${mode==='input'?'点数を入力':mode==='scores'?'成績を見る':'入力状況を見る'}</h1><p class="muted">${breadcrumbs()}</p></div><button data-action="change">条件を変更</button></div>${mode==='status'?`<div class="summary"><div>入力完了<b>${n}人</b></div><div>一部入力<b>${partial}人</b></div><div>未入力<b>${records.length-n-partial}人</b></div></div>`:''}<div class="panel"><div class="tools"><input id="search" class="search" placeholder="生徒名で検索" aria-label="生徒名で検索"><div class="segmented">${mode==='scores'?['score','dev'].map(m=>`<button data-metric="${m}" aria-pressed="${metric===m}">${m==='score'?'点数':'偏差値'}</button>`).join(''):mode==='status'?['all','missing','uncollected'].map((v,i)=>`<button data-filter="${v}" aria-pressed="${i===0}">${['すべて','未入力・一部入力','未回収'][i]}</button>`).join(''):''}</div><button data-action="reload">再読み込み</button></div>${mode==='scores'?'<p id="previousHint" class="hint" role="status"></p>':''}<div id="listTable" class="table-wrap ${mode==='input'||mode==='scores'?'score-table':''}"></div>${mode==='input'?`${master.capabilities.manager===true?'<button class="link" data-register="average">学校平均を入力・更新</button>':''}<p class="hint">Tabキーで次の欄へ。Excel等の5教科の点数を、最初の欄にまとめて貼り付けできます。0点と空欄は別に扱います。</p><div class="savebar"><p id="saveCount"></p><button id="saveAll" data-action="save" class="primary">変更を保存</button></div>`:'<button data-action="print" class="quiet">印刷する</button>'}</div><div id="history"></div>`;renderTable();}
let statusFilter='all',previousById=new Map(),previousLabel='',previousState='none';
function previousTest(){
 const tests=[...master.tests].sort((a,b)=>String(a.year).localeCompare(String(b.year))||(Number(a.order)||0)-(Number(b.order)||0));
 const index=tests.findIndex(t=>String(t.year)===String(selection.year)&&t.name===selection.test);
 return index>0?tests[index-1]:null;
}
function previousDelta(value,prior,kind){
 if(!present(value)||!present(prior)||!Number.isFinite(Number(value))||!Number.isFinite(Number(prior)))return '<small class="score-delta muted">前回比 —</small>';
 const n=Number(value)-Number(prior),shown=new Intl.NumberFormat('ja-JP',{maximumFractionDigits:2}).format(Math.abs(n));
 const level=n>=5?'gain':n<=(kind==='score'?-10:-5)?'drop':'neutral';
 return `<small class="score-delta ${level}" aria-label="前回比 ${n>0?'プラス':n<0?'マイナス':''}${shown}">${n>0?'+':n<0?'−':'±'}${shown}</small>`;
}
async function loadPrevious(token){
 const prior=previousTest();
 previousById=new Map();previousLabel=prior?`${prior.year}年度 ${prior.name}`:'';
 previousState=prior?'loading':'none';renderTable();
 if(!prior)return;
 try{
  const data=await request('records',{year:prior.year,test:prior.name,grade:selection.grade,school:''});
  if(token!==run||mode!=='scores'||view!=='list')return;
  previousById=new Map((data.records||[]).map(item=>[String(item.studentId),item.record]));
  previousState='ready';renderTable();
 }catch(e){if(token===run&&mode==='scores'&&view==='list'){previousState='error';renderTable()}}
}

function visibleRows(){const q=($('search')?.value||'').trim();return rows.filter(r=>r.student.name.includes(q)&&(mode!=='status'||statusFilter==='all'||statusFilter==='missing'&&(r.error||count(r.draft)<5)||statusFilter==='uncollected'&&(r.error||!r.saved||r.draft.collect==='未')))}
function renderTable(){const list=visibleRows();if(!$('listTable'))return;
if($('previousHint'))$('previousHint').textContent=previousState==='loading'?'前回の成績を確認中…':previousState==='ready'?'前回比：'+previousLabel:previousState==='error'?'前回比を取得できませんでした。成績は表示できます。':'比較できる前回のテストがありません。';
$('listTable').innerHTML=list.length?`<table><thead><tr><th>生徒</th>${mode==='status'?'<th>入力状況</th><th>回収</th>':SUB.map(s=>`<th>${s}${mode==='scores'&&metric==='dev'?' 偏差値':''}</th>`).join('')+(mode==='scores'&&metric==='score'?'<th>5科合計</th>':'')+'<th>詳細</th>'}</tr></thead><tbody>${list.map(r=>rowHTML(r)).join('')}</tbody></table>`:'<p class="empty">該当する生徒はいません。</p>';updateSaveCount();}
function rowHTML(r){const id=esc(r.student.id),rec=r.draft,changed=dirty(r),prior=previousById.get(r.student.id);let cells='';if(r.error)cells=`<td class="row-error" colspan="${mode==='status'?2:mode==='scores'&&metric==='score'?7:6}"><span class="error-text">取得できませんでした：${esc(r.error)}</span></td>`;else if(mode==='status')cells=`<td data-label="入力状況">${count(rec)===5?'入力完了':count(rec)?'一部入力':'未入力'}（${count(rec)} / 5科）</td><td data-label="回収">${r.saved&&rec.collect==='○'?'回収済':'未回収'}</td>`;else{cells=SUB.map(s=>`<td data-label="${s}${mode==='scores'&&metric==='dev'?' 偏差値':''}" class="${changed?'changed':''}">${mode==='input'?`<input data-id="${id}" data-sub="${s}" data-field="score" aria-label="${esc(r.student.name)} ${s} 点数" inputmode="decimal" value="${esc(rec.scores[s].score)}" ${busy?'disabled':''}>`:`${esc(present(rec.scores[s][metric])?rec.scores[s][metric]:'—')}${metric==='score'?`<small>学校平均 ${esc(present(rec.scores[s].avg)?rec.scores[s].avg:'—')}</small>`:''}${mode==='scores'&&previousState==='ready'?previousDelta(rec.scores[s][metric],prior?.scores?.[s]?.[metric],metric):''}`}</td>`).join('');if(mode==='scores'&&metric==='score')cells+=`<td data-label="5科合計" class="numeric">${count(rec)===5?SUB.reduce((n,s)=>n+Number(rec.scores[s].score),0):'—'}</td>`;cells+=`<td class="row-detail"><button class="details-button" data-detail="${id}">${mode==='input'?'詳細':'過去の成績'}</button></td>`}
return `<tr><td class="student-cell"><span class="name">${esc(r.student.name)}</span><span class="school-line">${esc(r.student.grade)} ／ ${esc(r.student.school||'学校未設定')}</span><span class="row-state" data-row-state="${id}">${esc(r.message||(changed?'未保存':r.saved?'保存済み':'未入力'))}</span></td>${cells}</tr>${mode==='input'&&extraOpen.has(r.student.id)?`<tr class="detail-row"><td colspan="7">${detailFields(r)}</td></tr>`:''}`}
function detailFields(r){const id=esc(r.student.id);return `<div class="detail-fields">${SUB.map(s=>`<div class="field"><label>${s} 偏差値</label><input data-id="${id}" data-sub="${s}" data-field="dev" inputmode="decimal" value="${esc(r.draft.scores[s].dev)}" ${busy?'disabled':''}></div>`).join('')}</div><div class="field-grid"><div class="field"><label>順位</label><input data-id="${id}" data-field="rank" inputmode="numeric" value="${esc(r.draft.rank)}" ${busy?'disabled':''}></div><div class="field"><label>回収</label><select data-id="${id}" data-field="collect" ${busy?'disabled':''}><option value="未" ${r.draft.collect==='未'?'selected':''}>未回収</option><option value="○" ${r.draft.collect==='○'?'selected':''}>回収済</option></select></div><div class="field full"><label>メモ</label><textarea data-id="${id}" data-field="memo" ${busy?'disabled':''}>${esc(r.draft.memo)}</textarea></div></div>`}
function updateSaveCount(){const n=rows.filter(dirty).length;if($('saveCount'))$('saveCount').textContent=busy?'保存中です。画面を閉じずにお待ちください。':n?`${n}人の変更が未保存です。`:'変更はすべて保存済みです。';if($('saveAll')){$('saveAll').textContent=busy?'保存中…':`変更した${n}人を保存`;$('saveAll').disabled=busy||n===0}}
const RECORD_CACHE_PREFIX='kyowa-manager-records:v1:';
function recordsKey(){return RECORD_CACHE_PREFIX+JSON.stringify([selection.year,selection.test,selection.grade,selection.school])}
function cachedRecords(){try{const saved=JSON.parse(sessionStorage.getItem(recordsKey())||'null');return saved&&Date.now()-saved.at<6*60*60*1000&&Array.isArray(saved.records)?saved.records:null}catch(_){return null}}
function keepRecords(records){try{sessionStorage.setItem(recordsKey(),JSON.stringify({at:Date.now(),records}))}catch(_){}}
function clearRecordCache(){try{for(let i=sessionStorage.length-1;i>=0;i--){const key=sessionStorage.key(i);if(key?.startsWith(RECORD_CACHE_PREFIX))sessionStorage.removeItem(key)}}catch(_){}}
function rowsFromRecords(records){const byId=new Map(records.map(r=>[String(r.studentId),r]));return master.students.filter(s=>s.status==='在籍'&&s.grade===selection.grade&&(selection.school==='__all__'||(selection.school==='__unset__'?!s.school:s.school===selection.school))&&Number(s.startYear||0)<=Number(selection.year)).map(student=>{const found=byId.get(student.id),rec=normalize(found?.record);return {student,saved:!!found?.record,base:clone(rec),draft:rec,error:found?null:'一覧に含まれていません',message:''}})}
async function fetchRecords(){const data={year:selection.year,test:selection.test,grade:selection.grade,school:['__unset__','__all__'].includes(selection.school)?'':selection.school};try{return await request('records',data)}catch(e){if(!/通信エラー（(?:404|429|5[0-9][0-9])）|Failed to fetch|Load failed|NetworkError/i.test(e.message))throw e;await new Promise(resolve=>setTimeout(resolve,600));return request('records',data)}}
async function loadRows(){
 const token=++run,cached=mode==='scores'||mode==='status'?cachedRecords():null;
 rows=cached?rowsFromRecords(cached):[];previousById=new Map();previousLabel='';previousState='none';statusFilter='all';view=cached?'list':'loading';render();
 notice(cached?'前回の成績を表示中です。最新データを確認しています…':'');
 try{
  const result=await fetchRecords();if(token!==run)return;
  if(!Array.isArray(result.records))throw Error('一覧を読み込めませんでした');
  keepRecords(result.records);rows=rowsFromRecords(result.records);view='list';notice();render();if(mode==='scores')loadPrevious(token);
  if(mode==='input'&&master.capabilities.manager===true&&!['__unset__','__all__'].includes(selection.school)){
   try{const av=await request('averages',{year:selection.year,test:selection.test,grade:selection.grade,school:selection.school});
    if(token===run){rows.filter(r=>!r.saved).forEach(r=>SUB.forEach(s=>{r.base.scores[s].avg=av.averages?.[s]?.avg??'';r.draft.scores[s].avg=r.base.scores[s].avg}));renderTable()}}
   catch(e){if(token===run)notice('学校平均を取得できませんでした：'+e.message,true)}
  }
 }catch(e){if(token!==run)return;view='list';notice(cached?'前回の成績を表示しています。最新化できませんでした：'+e.message:e.message,true);render()}
}
function payload(r){return {year:selection.year,test:selection.test,grade:r.student.grade,studentId:r.student.id,...clone(r.draft)}}
function validate(rec){for(const s of SUB){for(const field of ['score','dev']){const v=String(rec.scores[s][field]??'').trim();if(v&&!/^\d+(\.\d+)?$/.test(v))throw Error(s+'の'+(field==='score'?'点数':'偏差値')+'は数値で入力してください');if(v&&(+v<0||+v>100))throw Error(s+'は0〜100で入力してください')}}if(present(rec.rank)&&(!/^\d+$/.test(String(rec.rank))||Number(rec.rank)<1))throw Error('順位は1以上の整数で入力してください');if(rec.memo.length>2000)throw Error('メモは2000文字以内にしてください')}
async function saveAll(){if(busy)return;const pending=rows.filter(dirty);try{pending.forEach(r=>validate(r.draft))}catch(e){notice(e.message,true);return}busy=true;renderTable();updateSaveCount();let failures=0;
for(const r of pending){r.message='保存中…';renderTable();try{const live=await request('record',{year:selection.year,test:selection.test,studentId:r.student.id});if(fingerprint(normalize(live.record))!==fingerprint(r.base))throw Error('ほかの人が変更しました。入力内容を控えて再読み込みしてください');const p=payload(r);p.expectedRecord=fingerprint(r.base);const result=await request('save',p,true);if(!result.record)throw Error('保存結果を確認できませんでした');r.draft=normalize(result.record);r.base=clone(r.draft);r.saved=true;clearRecordCache();r.message=result.manualSync?.ok===false?'成績は保存済み。手入力タブの反映を確認してください。':'保存しました'}catch(e){failures++;r.message=e.message}}
busy=false;renderTable();notice(failures?`${failures}人を保存できませんでした。入力内容は残っています。`:`${pending.length}人の成績を保存しました。`,!!failures)}
function edit(target){const r=rows.find(r=>r.student.id===target.dataset.id);if(!r||r.error||busy)return;const f=target.dataset.field;if(target.dataset.sub)r.draft.scores[target.dataset.sub][f]=target.value;else r.draft[f]=target.value;if(f==='score'&&present(target.value))r.draft.collect='○';r.message='';const cell=target.closest('td');if(cell)cell.classList.toggle('changed',dirty(r));document.querySelectorAll('[data-row-state]').forEach(el=>{if(el.dataset.rowState===r.student.id)el.textContent=dirty(r)?'未保存':r.saved?'保存済み':'未入力'});updateSaveCount()}
async function history(id){const st=master.students.find(s=>s.id===id);if(!st)return;const token=++run;const target=$('history');target.innerHTML='<div class="panel"><h2>過去の成績を読み込み中…</h2></div>';target.scrollIntoView({behavior:'smooth'});const results=[];try{if(master.capabilities.manager){const d=await request('history',{studentId:id});results.push(...d.history)}else for(const t of master.tests.filter(t=>Number(t.year)>=Number(st.startYear||0))){try{const d=await request('record',{year:t.year,test:t.name,studentId:id});results.push({year:t.year,test:t.name,record:d.record})}catch(e){results.push({year:t.year,test:t.name,error:e.message})}if(token!==run)return}if(token!==run)return;paintHistory(st,results)}catch(e){if(token===run)target.innerHTML=`<div class="panel error-text">${esc(e.message)}</div>`}}
let historyData=null,averageReadRun=0;
function paintHistory(st,results){historyData={st,results};$('history').innerHTML=`<div class="panel"><div class="topline"><h2>${esc(st.name)}｜過去の成績</h2><button data-action="closeHistory">閉じる</button></div><div class="segmented">${['score','dev'].map(m=>`<button data-metric="${m}" aria-pressed="${metric===m}">${m==='score'?'点数':'偏差値'}</button>`).join('')}</div><p class="print-only">${metric==='score'?'点数':'偏差値'}</p><div class="table-wrap history-table"><table><thead><tr><th>年度・テスト</th>${SUB.map(s=>`<th>${s}</th>`).join('')}<th>順位</th></tr></thead><tbody>${results.map(d=>`<tr><td>${esc(d.year)} ／ ${esc(d.test)}${d.error?'<small class="error-text">取得失敗</small>':''}</td>${SUB.map(s=>`<td data-label="${s}">${esc(present(d.record?.scores?.[s]?.[metric])?d.record.scores[s][metric]:'—')}</td>`).join('')}<td data-label="順位">${esc(d.record?.rank||'—')}</td></tr>`).join('')}</tbody></table></div></div>`}
function selectHTML(name,label,values,current='',first='選択してください'){return `<div class="field"><label for="reg-${name}">${label}</label><select id="reg-${name}" name="${name}" required><option value="">${first}</option>${values.map(v=>`<option value="${esc(v)}" ${String(current)===String(v)?'selected':''}>${esc(v)}</option>`).join('')}</select></div>`}
function textHTML(name,label,type='text',value=''){return `<div class="field"><label for="reg-${name}">${label}</label><input id="reg-${name}" name="${name}" type="${type}" value="${esc(value)}" required ${type==='number'?'min="2000" max="2100"':''}></div>`}
function openRegistration(kind){if(busy)return;formKind=kind;$('registerStatus').textContent='';$('registerStatus').className='';const titles={student:'生徒を追加',school:'中学校を追加',test:'テストを追加',average:'学校平均を入力',assign:'生徒の学校を変更'};$('registerTitle').textContent=titles[kind];const years=[...new Set(master.tests.map(t=>String(t.year)))].sort().reverse();let content='';
if(kind==='student')content=textHTML('name','生徒名')+selectHTML('grade','学年',['中1','中2','中3'])+selectHTML('school','中学校',master.schools)+textHTML('year','登録年度','number',selection.year)+ '<p class="hint">生徒IDは自動で発行します。同姓同名が見つかった場合は登録を止めて確認します。</p>';
if(kind==='school')content=textHTML('name','中学校名')+'<p class="hint">例：大府北。登録後、入力や閲覧の候補に反映します。</p>';
if(kind==='test')content=textHTML('year','年度','number',selection.year)+textHTML('name','テスト名')+selectHTML('copyYear','前年度からまとめてコピー（任意）',years,'','コピーしない')+'<p class="hint">コピーする場合、テスト名の入力は不要です。</p>';
if(kind==='average')content=selectHTML('school','中学校',master.schools,selection.school)+selectHTML('grade','学年',['中1','中2','中3'],selection.grade)+selectHTML('year','年度',years,selection.year)+selectHTML('test','テスト',master.tests.filter(t=>String(t.year)===selection.year).map(t=>t.name),selection.test)+`<div class="field-grid">${SUB.map((s,i)=>`<div class="field"><label for="reg-avg${i}">${s} 平均点</label><input name="avg${i}" id="reg-avg${i}" type="number" min="0" max="100" step="any" placeholder="未入力"></div>`).join('')}</div><button type="button" data-action="readAverage" class="quiet">登録済みの平均を読み込む</button><p class="hint">空欄の教科は未登録として保存します。成績履歴に保存済みの学校平均は、成績を再保存したときに更新します。</p>`;
if(kind==='assign')content=`<div class="field"><label for="reg-studentId">生徒</label><select id="reg-studentId" name="studentId" required><option value="">生徒を選択</option>${master.students.filter(s=>s.status==='在籍').map(s=>`<option value="${esc(s.id)}">${esc(s.name)}（${esc(s.grade)}・${esc(s.school||'学校未設定')}）</option>`).join('')}</select></div>`+selectHTML('school','中学校',master.schools);
$('registerFields').innerHTML=content;if(kind==='test'){$('reg-copyYear').required=false;$('reg-copyYear').onchange=()=>{$('reg-name').required=!$('reg-copyYear').value;$('reg-name').disabled=!!$('reg-copyYear').value}}
if(kind==='average')$('reg-year').onchange=()=>{$('reg-test').innerHTML='<option value="">選択してください</option>'+master.tests.filter(t=>String(t.year)===$('reg-year').value).map(t=>`<option>${esc(t.name)}</option>`).join('');readAverage(true)};if(kind==='average')['school','grade','test'].forEach(k=>$('reg-'+k).onchange=()=>readAverage(true));$('registerSubmit').disabled=kind!=='assign'&&master.capabilities.manager!==true;$('registerSubmit').textContent=kind==='assign'?'学校を名簿に保存':kind==='average'?'学校平均を保存':'登録する';if($('registerSubmit').disabled)$('registerStatus').textContent='接続先の更新後に登録できます。設定手順は「登録・設定」にあります。';$('registration').showModal();if(kind==='average')readAverage(true)}
async function submitRegistration(event){event.preventDefault();if(busy||$('registerSubmit').disabled)return;const data=Object.fromEntries(new FormData($('registerForm'))),kind=formKind;busy=true;$('registerSubmit').disabled=true;$('closeDialog').disabled=true;$('registerStatus').textContent='保存中…';try{let result;if(kind==='assign'){const st=master.students.find(s=>s.id===data.studentId);result=await request('school',{studentId:st.id,school:data.school,previousSchool:st.school||''},true)}else{if(kind==='average')data.averages=Object.fromEntries(SUB.map((s,i)=>[s,data['avg'+i]||'']));result=await request('managerSave',{kind,...data},true)}await refreshMaster(false);if(kind==='average'&&view==='list'&&data.school===selection.school&&data.grade===selection.grade&&data.year===selection.year&&data.test===selection.test){rows.forEach(r=>SUB.forEach(s=>r.draft.scores[s].avg=data.averages[s]));renderTable()}$('registerStatus').textContent=result.message||'保存しました。';notice(result.message||'登録しました。');if(kind==='average')$('registerSubmit').textContent='学校平均を保存';else $('registration').close()}catch(e){$('registerStatus').textContent=e.message;$('registerStatus').className='error-text'}finally{busy=false;$('registerSubmit').disabled=false;$('closeDialog').disabled=false}}
async function readAverage(automatic=false){
const token=++averageReadRun;
if(master.capabilities.manager!==true){$('registerStatus').textContent='登録済み平均の取得には接続先の更新が必要です。';return}
const d=Object.fromEntries(new FormData($('registerForm')));
if(!d.year||!d.test||!d.grade||!d.school){$('registerSubmit').disabled=busy;SUB.forEach((_,i)=>$('reg-avg'+i).disabled=false);if(automatic)SUB.forEach((_,i)=>$('reg-avg'+i).value='');$('registerStatus').textContent='学校・学年・年度・テストを選択してください。';return}
if(automatic)SUB.forEach((_,i)=>$('reg-avg'+i).value='');
SUB.forEach((_,i)=>$('reg-avg'+i).disabled=true);$('registerSubmit').disabled=true;$('registerStatus').textContent='登録済みの学校平均を読み込み中…';
try{const r=await request('averages',d);if(token!==averageReadRun||formKind!=='average')return;SUB.forEach((s,i)=>$('reg-avg'+i).value=r.averages?.[s]?.avg??'');$('registerStatus').textContent=SUB.some(s=>present(r.averages?.[s]?.avg))?'登録済みの学校平均を表示しています。':'この条件の学校平均は未登録です。'}
catch(e){if(token===averageReadRun&&formKind==='average')$('registerStatus').textContent='学校平均を取得できませんでした：'+e.message}
finally{if(token===averageReadRun&&formKind==='average'){SUB.forEach((_,i)=>$('reg-avg'+i).disabled=busy);$('registerSubmit').disabled=busy}}
}
async function refreshMaster(show=true){if(show)notice('最新の名簿とテストを確認中…');try{const d=await request('bootstrap');if(!Array.isArray(d.students)||!Array.isArray(d.tests))throw Error('名簿の形式を確認してください');master=d;master.schools=d.schools||[];ready=true;if(show){notice('名簿を更新しました。');render()}}catch(e){notice(e.message,true);if(show)render();throw e}}
$('settings').onclick=()=>{if(!leave())return;view='settings';render()};$('brand').onclick=e=>{e.preventDefault();home()};$('closeDialog').onclick=()=>{if(!busy)$('registration').close()};$('registration').addEventListener('cancel',e=>{if(busy)e.preventDefault()});$('registerForm').onsubmit=submitRegistration;
$('app').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.start){start(b.dataset.start);return}if(b.dataset.choice){choose(b.dataset.choice);return}if(b.dataset.register){openRegistration(b.dataset.register);return}if(b.dataset.metric){metric=b.dataset.metric;document.querySelectorAll('[data-metric]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.metric===metric)));renderTable();if(historyData&&$('history')?.innerHTML)paintHistory(historyData.st,historyData.results);return}if(b.dataset.filter){statusFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderTable();return}if(b.dataset.detail){if(mode==='input'){extraOpen.has(b.dataset.detail)?extraOpen.delete(b.dataset.detail):extraOpen.add(b.dataset.detail);renderTable()}else history(b.dataset.detail);return}const a=b.dataset.action;if(a==='home')home();if(a==='back'){if(step>0){step--;render()}else home()}if(a==='change'){if(leave()){view='choose';step=0;render()}}if(a==='reload'&&leave())loadRows();if(a==='save')saveAll();if(a==='refresh'&&!busy)refreshMaster().catch(()=>{});if(a==='print')window.print();if(a==='closeHistory'){run++;historyData=null;$('history').innerHTML=''}});
$('app').addEventListener('input',e=>{if(e.target.id==='search')renderTable();else if(e.target.dataset.field)edit(e.target)});$('app').addEventListener('change',e=>{if(e.target.dataset.field)edit(e.target)});
$('registerFields').addEventListener('click',e=>{if(e.target.closest('[data-action="readAverage"]'))readAverage()});
$('app').addEventListener('paste',e=>{const target=e.target;if(mode!=='input'||busy||target.dataset.field!=='score')return;const text=e.clipboardData.getData('text');if(!/[\t\n]/.test(text))return;const values=text.replace(/\r?\n$/, '').split(/\r?\n/).map(r=>r.split('\t')),visible=visibleRows(),rowIndex=visible.findIndex(r=>r.student.id===target.dataset.id),colIndex=SUB.indexOf(target.dataset.sub);e.preventDefault();if(values.some(v=>v.length+colIndex>5)||values.length+rowIndex>visible.length){notice('貼り付ける行・列が表示範囲を超えています。5教科の点数だけをコピーしてください。',true);return}try{values.forEach((line,i)=>{const candidate=clone(visible[rowIndex+i].draft);line.forEach((v,j)=>candidate.scores[SUB[colIndex+j]].score=v.trim());validate(candidate)});values.forEach((line,i)=>{line.forEach((v,j)=>visible[rowIndex+i].draft.scores[SUB[colIndex+j]].score=v.trim());if(line.some(v=>v.trim()!==''))visible[rowIndex+i].draft.collect='○'});renderTable();notice('点数を貼り付けました。「変更を保存」で保存してください。')}catch(err){notice(err.message,true)}});
window.addEventListener('beforeunload',e=>{if(busy||rows.some(dirty)){e.preventDefault();e.returnValue=''}});
let demoRecords={};
function demoMaster(){return {ok:true,schools:['大府西','大府北','大府南'],tests:[{year:'2026',name:'第1回',order:1},{year:'2026',name:'第2回',order:2}],students:[{id:'DEMO-1',name:'サンプル生徒 A',grade:'中3',school:'大府西',status:'在籍',startYear:'2026'},{id:'DEMO-2',name:'サンプル生徒 B',grade:'中3',school:'大府西',status:'在籍',startYear:'2026'},{id:'DEMO-3',name:'サンプル生徒 C',grade:'中2',school:'大府北',status:'在籍',startYear:'2026'}],capabilities:{records:true,schoolUpdate:true,schoolMaster:true,manager:true}}}
let demoData=demoMaster();
async function demoRequest(action,d={}){const key=[d.year,d.test,d.studentId].join('|');if(action==='bootstrap')return clone(demoData);if(action==='records')return {ok:true,records:demoData.students.map(s=>({studentId:s.id,record:demoRecords[[d.year,d.test,s.id].join('|')]||null}))};if(action==='record')return {ok:true,record:demoRecords[key]||null};if(action==='save'){demoRecords[key]=normalize(d);return {ok:true,record:clone(demoRecords[key])}}if(action==='school'){demoData.students.find(s=>s.id===d.studentId).school=d.school;return {ok:true}}if(action==='averages')return {ok:true,averages:Object.fromEntries(SUB.map(s=>[s,{avg:60}]))};if(action==='history')return {ok:true,history:demoData.tests.map(t=>({year:t.year,test:t.name,record:demoRecords[[t.year,t.name,d.studentId].join('|')]||null}))};if(action==='managerSave'){if(d.kind==='school'){if(demoData.schools.includes(d.name))throw Error('同じ学校名が登録されています');demoData.schools.push(d.name)}if(d.kind==='student')demoData.students.push({id:'DEMO-'+Date.now(),name:d.name,school:d.school,grade:d.grade,startYear:d.year,status:'在籍'});if(d.kind==='test'){const names=d.copyYear?demoData.tests.filter(t=>t.year===d.copyYear).map(t=>t.name):[d.name];names.forEach((name,i)=>{if(!demoData.tests.some(t=>t.year===d.year&&t.name===name))demoData.tests.push({year:d.year,name,order:i+1})})}return {ok:true,message:'体験データに保存しました。'}}throw Error('未対応の処理です')}

let rosterSelected=new Set(),rosterMessages=new Map(),rosterFilters={grade:'',school:'',query:''},rosterSchool='';
function rosterVisible(){return master.students.filter(s=>s.status==='在籍'&&(!rosterFilters.grade||s.grade===rosterFilters.grade)&&(!rosterFilters.school||(rosterFilters.school==='__unset__'?!s.school:s.school===rosterFilters.school))&&(!rosterFilters.query||s.name.includes(rosterFilters.query)||s.id.includes(rosterFilters.query)))}
function renderRoster(){
const active=master.students.filter(s=>s.status==='在籍'),grades=[...new Set(active.map(s=>s.grade))].sort();
$('app').innerHTML=`<button class="back quiet" data-action="home" ${busy?'disabled':''}>← ホーム</button><h1>生徒一覧</h1><p class="muted">在籍 ${active.length}人</p><div class="panel"><div class="roster-filters"><input class="search" id="rosterQuery" aria-label="生徒名・IDで検索" placeholder="生徒名・IDで検索" value="${esc(rosterFilters.query)}" ${busy?'disabled':''}><select id="rosterGrade" aria-label="学年で絞り込み" ${busy?'disabled':''}><option value="">すべての学年</option>${grades.map(g=>`<option value="${esc(g)}" ${g===rosterFilters.grade?'selected':''}>${esc(g)}</option>`).join('')}</select><select id="rosterFilterSchool" aria-label="学校で絞り込み" ${busy?'disabled':''}><option value="">すべての中学校</option><option value="__unset__" ${rosterFilters.school==='__unset__'?'selected':''}>学校未設定</option>${master.schools.map(g=>`<option value="${esc(g)}" ${g===rosterFilters.school?'selected':''}>${esc(g)}</option>`).join('')}</select><button data-roster-action="refresh" ${busy?'disabled':''}>名簿を更新</button></div><div class="roster-selection"><button data-roster-action="selectVisible" ${busy?'disabled':''}>表示中をすべて選択</button><button data-roster-action="clear" ${busy?'disabled':''}>選択を解除</button><span id="rosterCount" role="status"></span></div><div class="table-wrap" id="rosterTable"></div><div class="savebar roster-save"><label for="rosterSchool">登録する学校</label><select id="rosterSchool" ${busy?'disabled':''}><option value="">学校を選択</option>${master.schools.map(g=>`<option value="${esc(g)}" ${g===rosterSchool?'selected':''}>${esc(g)}</option>`).join('')}</select><button class="primary" id="rosterSave" data-roster-action="save">選択した生徒に登録</button></div><p class="hint">選択した生徒全員の学校を変更します。学校の候補は「登録・設定」で追加できます。</p></div>`;
renderRosterTable();
}
function renderRosterTable(){
const list=rosterVisible();$('rosterTable').innerHTML=list.length?`<table class="roster-table"><thead><tr><th>選択</th><th>生徒名</th><th>学年</th><th>学校</th><th>生徒ID</th><th>登録結果</th></tr></thead><tbody>${list.map(s=>`<tr><td class="roster-check"><input type="checkbox" data-roster-id="${esc(s.id)}" aria-label="${esc(s.name)}を選択" ${rosterSelected.has(s.id)?'checked':''} ${busy?'disabled':''}></td><td class="roster-name">${esc(s.name)}</td><td data-label="学年">${esc(s.grade)}</td><td data-label="学校">${esc(s.school||'学校未設定')}</td><td data-label="生徒ID">${esc(s.id)}</td><td data-label="登録結果">${esc(rosterMessages.get(s.id)||'—')}</td></tr>`).join('')}</tbody></table>`:'<p class="empty">該当する生徒はいません。</p>';
updateRosterCount();
}
function updateRosterCount(){const visible=rosterVisible(),hidden=[...rosterSelected].filter(id=>!visible.some(s=>s.id===id)).length;$('rosterCount').textContent=`表示 ${visible.length}人 ／ 選択 ${rosterSelected.size}人`+(hidden?`（表示外 ${hidden}人を含む）`:'');$('rosterSave').disabled=busy||!rosterSelected.size||!rosterSchool;$('rosterSave').textContent=busy?'登録中…':`選択した${rosterSelected.size}人に登録`}
async function saveRosterSchool(){
if(busy||!rosterSelected.size||!master.schools.includes(rosterSchool))return;
const targetSchool=rosterSchool,pending=master.students.filter(s=>s.status==='在籍'&&rosterSelected.has(s.id));busy=true;renderRoster();let success=0,failed=0;
for(const st of pending){try{if((st.school||'')!==targetSchool){await request('school',{studentId:st.id,school:targetSchool,previousSchool:st.school||''},true);st.school=targetSchool}rosterMessages.set(st.id,'登録済み');rosterSelected.delete(st.id);success++}catch(e){rosterMessages.set(st.id,e.message);failed++}renderRosterTable()}
busy=false;renderRoster();notice(failed?`${success}人を登録しました。${failed}人は登録できませんでした。選択と結果を確認してください。`:`${success}人の学校を「${targetSchool}」に登録しました。`,!!failed);
}
$('app').addEventListener('input',e=>{if(e.target.id==='rosterQuery'&&!busy){rosterFilters.query=e.target.value.trim();renderRosterTable()}});
$('app').addEventListener('change',e=>{if(busy)return;const t=e.target;if(t.dataset.rosterId){t.checked?rosterSelected.add(t.dataset.rosterId):rosterSelected.delete(t.dataset.rosterId);updateRosterCount()}if(t.id==='rosterGrade'){rosterFilters.grade=t.value;renderRosterTable()}if(t.id==='rosterFilterSchool'){rosterFilters.school=t.value;renderRosterTable()}if(t.id==='rosterSchool'){rosterSchool=t.value;updateRosterCount()}});
$('app').addEventListener('click',e=>{const a=e.target.closest('[data-roster-action]')?.dataset.rosterAction;if(!a||busy)return;if(a==='selectVisible'){rosterVisible().forEach(s=>rosterSelected.add(s.id));renderRosterTable()}if(a==='clear'){rosterSelected.clear();renderRosterTable()}if(a==='save')saveRosterSchool();if(a==='refresh')refreshMaster().catch(()=>{})});

render();notice();refreshMaster(false).then(()=>{notice();render()}).catch(()=>render()).finally(()=>{$('startup').hidden=true});
