(() => {
'use strict';
const $=id=>document.getElementById(id), clone=x=>structuredClone(x), DURATION=232.4;
const A='editor-assets/', state={base:null,data:null,selected:null,view:'edit',zoom:9,history:[],future:[],wave:[],images:new Map(),renderer:null,plan:null,originalPlan:null,drag:null,recording:false};
const song=$('song'),ref=$('reference'),baseline=$('baseline'),canvas=$('screen'),ctx=canvas.getContext('2d'),overlay=document.createElement('canvas');overlay.width=960;overlay.height=540;const octx=overlay.getContext('2d');
const sec=n=>Math.max(0,Math.min(DURATION,+n||0)), fmt=n=>{n=sec(n);return `${String(Math.floor(n/60)).padStart(2,'0')}:${(n%60).toFixed(2).padStart(5,'0')}`};
const key=(type,id)=>type+':'+id, item=(type,id,data=state.data)=>data?.[type]?.find(x=>x.id===id);
const selected=()=>state.selected&&item(state.selected.type,state.selected.id);
const changed=(type,x)=>{const original=item(type,x.id,state.base);return !original||JSON.stringify(x)!==JSON.stringify(original)};
const tell=s=>{$('status').textContent=s;clearTimeout(tell.timer);tell.timer=setTimeout(()=>$('status').textContent='',4500)};
function save(){try{localStorage.setItem('bye-bye-blue-v5',JSON.stringify(state.data));tell('この端末に保存しました')}catch{tell('保存容量が不足しています。編集データを書き出してください')}}
function record(before){state.history.push(before||clone(state.data));if(state.history.length>80)state.history.shift();state.future=[];save();refresh()}
function refresh(){timeline();inspector();draw();$('undo').disabled=!state.history.length;$('redo').disabled=!state.future.length;changes()}
function setTime(t){song.currentTime=sec(t);renderTime();draw();syncReference(true)}
function renderTime(){let t=sec(song.currentTime);$('seek').value=t;$('clock').textContent=`${fmt(t)} / ${fmt(DURATION)}`;$('playhead').style.left=(t*state.zoom)+'px'}
function syncReference(force=false){for(const video of [ref,baseline])if(force||Math.abs(video.currentTime-song.currentTime)>.13){try{video.currentTime=song.currentTime}catch{}}}
function active(xs,t){return xs.filter(x=>x.start<=t&&t<x.end).at(-1)}
function imageFor(p){return state.images.get(p.asset)}
function cutMode(n){if(n<=12)return ['assemble','track','type','assemble','track','type','assemble','type','assemble','assemble','track','type','assemble'][n];if(n<=20)return ['slide','type','slide','track','slide','type','slide','track'][n-13];if(n<=31)return ['band','key','huge','type','band','phrase','type','huge','band','track','huge'][n-21];if(n<=43)return cutMode(n-33);if(n<=51)return cutMode(n-31);if(n<=58)return cutMode(n-31);if(n<=67)return n%2?'band':'phrase';if(n>=69)return cutMode(21+(n-69)%11);return 'assemble'}
const panelSides={7:'left',9:'left',11:'right',15:'left',17:'right',19:'right',40:'right',42:'left',46:'left',48:'right',50:'right'};
function makePlan(data){const p=J.plan(data.project,{duration:232.44,beats:[]}),lookup=new Map(data.lyrics.filter(x=>x.line!==undefined).map(x=>[x.line,x]));p.cuts=p.cuts.filter(c=>lookup.has(c.line));for(const x of data.lyrics.filter(x=>x.line===undefined)){const c={...p.cuts[0],line:1000+p.cuts.length};lookup.set(c.line,x);p.cuts.push(c)}for(const c of p.cuts){const x=lookup.get(c.line);c.start=x.start;c.end=x.end;c.dur=c.end-c.start;c.text=x.text;c.layout='bbEditorial';c.params={mode:x.mode,edits:{x:x.x,y:x.y,scale:x.scale,rotation:x.rotation,tracking:x.tracking,lineBreak:x.lineBreak,lineSpacing:x.lineSpacing,align:x.align,enterEffect:x.enterEffect,exitEffect:x.exitEffect,panelSide:x.panelSide,panelWidth:x.panelWidth,panelPosition:x.panelPosition,panelMotion:x.panelMotion,bandWidth:x.bandWidth,bandHeight:x.bandHeight,bandAngle:x.bandAngle,bandPosition:x.bandPosition,bandMotion:x.bandMotion,bandStart:x.bandStart,bandEnd:x.bandEnd}};c.enter='cut';c.hold='still';c.exit='cut';c.treat=null;c.decor=[];c.trans=null;c.morph=null;c.cam='push';c.bg='none'}p.cuts.sort((a,b)=>a.start-b.start);p.cuts.forEach((c,i)=>c.index=i);p.events=[];p.beats=[];p.fx.chroma=0;p.style.ghost=0;p.hud=false;return p}
function updatePlan(){state.plan=makePlan(state.data)}
function draw(){if(!state.data)return;const t=sec(song.currentTime),p=active(state.data.photos,t)||state.data.photos[0],im=p&&imageFor(p);ctx.clearRect(0,0,960,540);const photoChanged=p&&changed('photos',p),lyric=active(state.data.lyrics,t),lyricChanged=lyric&&changed('lyrics',lyric);if(photoChanged||lyricChanged){ctx.fillStyle='#0b1018';ctx.fillRect(0,0,960,540);
 if(im?.complete&&im.naturalWidth){const u=Math.max(0,Math.min(1,(t-p.start)/Math.max(.1,p.end-p.start))),dur=p.end-p.start,span=dur<3||t>=160.10&&t<177.70?0:Math.min(dur*1.2,960*.012),zoom=(p.scale||1)*(1+(p.zoomAmount||0)*(u-.5)),cw=960*1.025/zoom,ch=540*1.025/zoom,dx=(im.width-cw)/2+(u-.5)*(p.panAmount??1)*span+(p.x||0)*960,dy=(im.height-ch)/2+(p.y||0)*540;if(p.crossfade>0&&t<p.start+p.crossfade){const i=state.data.photos.indexOf(p),prev=state.data.photos[i-1],prior=prev&&imageFor(prev);if(prior?.complete&&prior.naturalWidth){const zw=(prev.scale||1)*(1+(prev.zoomAmount||0)*.5),pw=960*1.025/zw,ph=540*1.025/zw;ctx.drawImage(prior,(prior.width-pw)/2+(prev.x||0)*960,(prior.height-ph)/2+(prev.y||0)*540,pw,ph,0,0,960,540)}}ctx.globalAlpha=Math.min(1,(t-p.start)/Math.max(.001,p.fadeIn||0.001),(p.end-t)/Math.max(.001,p.fadeOut||0.001),p.crossfade>0?(t-p.start)/p.crossfade:1);ctx.drawImage(im,dx,dy,cw,ch,0,0,960,540);ctx.globalAlpha=1;if(p.cut===39){ctx.fillStyle='#ffffff1a';ctx.fillRect(0,0,960,540)}}
 else{ctx.fillStyle='#9daebe';ctx.fillText('写真を読み込み中…',25,35)}
 try{state.renderer.frame(octx,state.plan,t,{scale:960/state.plan.W,transparent:true,noGhost:true,noTrans:true,noPost:true,noHud:true,fast:true});ctx.drawImage(overlay,0,0)}catch(e){if(!draw.warned){console.error(e);tell('JIZURA描画を確認中です');draw.warned=true}}
 }if(state.selected&&state.view==='edit'){const s=selected();if(s&&s.start<=t&&t<s.end){ctx.strokeStyle='#6ee7f5';ctx.lineWidth=1.5;ctx.setLineDash([7,5]);if(state.selected.type==='lyrics'){ctx.strokeRect(960*(.12+s.x),540*(.25+s.y),960*.76,540*.48);ctx.fillStyle='#6ee7f5';ctx.fillRect(960*(.88+s.x)-8,540*(.73+s.y)-8,16,16)}else ctx.strokeRect(4,4,952,532);ctx.setLineDash([])}}}
function timeline(){if(!state.data)return;const z=state.zoom,w=DURATION*z;$('timelineInner').style.setProperty('--tw',w+'px');$('ruler').replaceChildren();for(let t=0;t<=DURATION;t+=10){const el=document.createElement('span');el.className='tick';el.style.left=t*z+'px';el.textContent=fmt(t).slice(0,5);$('ruler').append(el)}
 for(const [type,target] of [['photos',$('photos')],['lyrics',$('lyrics')]]){target.querySelectorAll('.clip').forEach(e=>e.remove());for(const x of state.data[type]){let el=document.createElement('div');el.className=`clip ${type==='lyrics'?'lyric':''} ${changed(type,x)?'changed':''} ${state.selected?.type===type&&state.selected.id===x.id?'selected':''}`;el.style.left=x.start*z+'px';el.style.width=Math.max(8,(x.end-x.start)*z)+'px';el.textContent=type==='photos'?`${x.cut||'＋'} ${x.label||x.asset}`:x.text;el.dataset.type=type;el.dataset.id=x.id;for(const side of ['left','right']){let h=document.createElement('span');h.className='handle '+side;h.dataset.handle=side;el.append(h)}target.append(el)}}
 $('effects').querySelectorAll('.clip').forEach(e=>e.remove());for(const x of state.data.lyrics.filter(x=>x.mode==='band'||x.panelSide&&x.panelSide!=='off')){let el=document.createElement('div');el.className='clip effect '+(changed('lyrics',x)?'changed':'');el.style.left=x.start*z+'px';el.style.width=Math.max(8,(x.end-x.start)*z)+'px';el.textContent=x.mode==='band'?'斜め白帯':'左右隠し';el.dataset.type='lyrics';el.dataset.id=x.id;$('effects').append(el)}renderTime()}
function waveform(){const peaks=state.wave,w=DURATION*state.zoom;let path='';peaks.forEach((v,i)=>{let x=(i/peaks.length*w).toFixed(1),h=Math.max(1,v*22);path+=`M${x} ${23-h.toFixed(1)}V${(23+h).toFixed(1)}`});$('wave').querySelector('svg')?.remove();$('wave').insertAdjacentHTML('beforeend',`<svg viewBox="0 0 ${w} 46" preserveAspectRatio="none"><path d="${path}" stroke="#68bfd9" stroke-width="1" opacity=".8"/></svg>`)}
function changes(){let list=$('changesList');list.replaceChildren();const rows=[];for(const type of ['photos','lyrics'])for(const x of state.data[type])if(changed(type,x))rows.push({type,x});$('changesSummary').textContent=`変更した項目（${rows.length}）`;for(const {type,x} of rows){let b=document.createElement('button');b.textContent=`${type==='photos'?'写真':'歌詞'} ${fmt(x.start)} ${type==='photos'?x.label:x.text}`;b.onclick=()=>choose(type,x.id);list.append(b)}}
const field=(title,name,value,attrs='')=>`<label class="field">${title}<input data-field="${name}" value="${String(value??'').replaceAll('&','&amp;').replaceAll('"','&quot;')}" ${attrs}></label>`;
const number=(title,name,value,step=.01,min='')=>field(title,name,value,`type="number" step="${step}" ${min!==''?`min="${min}"`:''}`);
const timeField=(title,name,value)=>`<div class="field">${title}<input data-field="${name}" type="number" min="0" max="232.4" step="0.01" value="${Number(value).toFixed(2)}"><div class="micro">${[-1,-.1,-.01,.01,.1,1].map(d=>`<button data-nudge="${name}" data-delta="${d}">${d>0?'+':''}${d}</button>`).join('')}</div></div>`;
function inspector(){const x=selected(),type=state.selected?.type;$('resetItem').disabled=!x||!changed(type,x);$('changedBadge').hidden=!x||!changed(type,x);if(!x){$('itemTitle').textContent='素材を選択';$('editor').innerHTML='<div class="empty">下の写真・歌詞トラックから、直したい素材をクリックしてください。</div>';return}
 $('itemTitle').textContent=type==='photos'?`写真 ${x.cut||'追加'}｜${x.label||x.asset}`:`歌詞 ${x.line!==undefined?x.line+1:'追加'}｜${x.text.slice(0,18)}`;
 let html='<div class="fields">';if(type==='lyrics')html+=`<label class="field full">歌詞本文・改行<textarea data-field="text">${x.text.replaceAll('&','&amp;').replaceAll('<','&lt;')}</textarea></label>`;
 html+=timeField('表示開始', 'start',x.start)+timeField('表示終了','end',x.end)+number('表示時間（秒）','duration',(x.end-x.start).toFixed(2));
 if(type==='photos')html+=`</div><details class="group" open><summary>写真の位置と動き</summary><div class="fields">${number('X位置（画面幅比）','x',x.x,.001)}${number('Y位置（画面高比）','y',x.y,.001)}${number('拡大率','scale',x.scale,.001,.5)}${number('微パン量（負数は逆方向）','panAmount',x.panAmount,.01)}${number('微ズーム量','zoomAmount',x.zoomAmount,.001,0)}${number('フェードイン秒','fadeIn',x.fadeIn,.01,0)}${number('フェードアウト秒','fadeOut',x.fadeOut,.01,0)}${number('クロスフェード秒','crossfade',x.crossfade,.01,0)}<label class="field full">画像を差し替え<input id="replaceImage" type="file" accept="image/*"></label></div></details>`;
 else html+=`</div><details class="group" open><summary>文字の演出と位置</summary><div class="fields"><label class="field full">演出<select data-field="mode">${[['assemble','組み立て表示'],['simple','シンプル表示'],['track','文字間を詰める'],['type','1文字ずつ表示'],['slide','スライド'],['band','斜め白帯'],['key','大文字強調'],['huge','大きな極太文字'],['phrase','フレーズ表示']].map(([v,n])=>`<option value="${v}" ${x.mode===v?'selected':''}>${n}</option>`).join('')}</select></label>${number('X位置（画面幅比）','x',x.x,.001)}${number('Y位置（画面高比）','y',x.y,.001)}${number('文字サイズ倍率','scale',x.scale,.01,.1)}${number('文字間隔','tracking',x.tracking,.01)}${number('改行位置（文字数・0は元の設定）','lineBreak',x.lineBreak,1,0)}${number('行間倍率','lineSpacing',x.lineSpacing,.01,.2)}<label class="field">文字揃え<select data-field="align">${[['center','中央'],['left','左'],['right','右']].map(([v,n])=>`<option value="${v}" ${x.align===v?'selected':''}>${n}</option>`).join('')}</select></label><label class="field">出現<select data-field="enterEffect">${[['original','現在の演出'],['fade','フェード']].map(([v,n])=>`<option value="${v}" ${x.enterEffect===v?'selected':''}>${n}</option>`).join('')}</select></label><label class="field">消える演出<select data-field="exitEffect">${[['original','現在の演出'],['fade','フェード']].map(([v,n])=>`<option value="${v}" ${x.exitEffect===v?'selected':''}>${n}</option>`).join('')}</select></label>${number('回転角度（度）','rotation',x.rotation,1)}<label class="field">左右隠し<select data-field="panelSide">${[['','元の設定'],['off','なし'],['left','左側'],['right','右側']].map(([v,n])=>`<option value="${v}" ${x.panelSide===v?'selected':''}>${n}</option>`).join('')}</select></label></div></details><details class="group"><summary>白帯・左右隠しの細部</summary><div class="fields">${number('白帯の幅（画面比・空欄は元の設定）','bandWidth',x.bandWidth,.01,0)}${number('白帯の高さ','bandHeight',x.bandHeight,.01,0)}${number('白帯の傾き','bandAngle',x.bandAngle,.005)}${number('白帯の位置','bandPosition',x.bandPosition,.01)}${number('白帯の移動量','bandMotion',x.bandMotion,.01,0)}${number('白帯・出現開始の差（秒）','bandStart',x.bandStart,.01)}${number('白帯・消える時刻の差（秒）','bandEnd',x.bandEnd,.01)}${number('隠す幅（画面比・空欄は元の設定）','panelWidth',x.panelWidth,.01,0)}${number('隠す位置','panelPosition',x.panelPosition,.01)}${number('隠す移動量','panelMotion',x.panelMotion,.01)}</div></details>`;
 $('editor').innerHTML=html;$('editor').querySelectorAll('[data-field]').forEach(el=>el.addEventListener('change',()=>editField(el.dataset.field,el.value)));$('editor').querySelectorAll('[data-nudge]').forEach(el=>el.onclick=()=>editField(el.dataset.nudge,Number(selected()[el.dataset.nudge])+Number(el.dataset.delta)));$('replaceImage')?.addEventListener('change',replaceImage)}
function choose(type,id,seek=true){state.selected={type,id};const x=selected();if(seek&&x)setTime(Math.min(x.end-.04,x.start+.2));refresh()}
function editField(name,value){let x=selected();if(!x)return;const before=clone(state.data);if(['text','mode','panelSide','align','enterEffect','exitEffect'].includes(name))x[name]=value;else if(name==='duration')x.end=sec(x.start+Math.max(.01,Number(value)||.01));else{x[name]=value===''?null:Number(value);if(['start','end'].includes(name))x[name]=sec(x[name])}if(x.end<=x.start){if(name==='start')x.end=Math.min(DURATION,x.start+.01);else x.start=Math.max(0,x.end-.01)}if(name==='start'||name==='end')setTime(x.start+.05);updatePlan();record(before)}
async function replaceImage(e){const file=e.target.files?.[0],x=selected();if(!file||!x)return;const before=clone(state.data),asset='replacement-'+x.id+'-'+Date.now();try{const db=await dbOpen();await dbPut(db,asset,file);const im=await loadImage(URL.createObjectURL(file));state.images.set(asset,im);x.asset=asset;updatePlan();record(before);tell('画像を差し替えました。時刻と演出は維持しています')}catch(err){console.error(err);tell('画像を保存できませんでした')}}
function loadImage(url){return new Promise((ok,no)=>{let im=new Image();im.onload=()=>ok(im);im.onerror=no;im.src=url})}
function dbOpen(){return new Promise((ok,no)=>{const q=indexedDB.open('bye-bye-blue-v5-images',1);q.onupgradeneeded=()=>q.result.createObjectStore('images');q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
function dbPut(db,k,v){return new Promise((ok,no)=>{let tx=db.transaction('images','readwrite');tx.objectStore('images').put(v,k);tx.oncomplete=ok;tx.onerror=()=>no(tx.error)})}
async function loadReplacements(){try{let db=await dbOpen();for(const p of state.data.photos.filter(x=>x.asset.startsWith('replacement-'))){let blob=await new Promise(ok=>{let q=db.transaction('images').objectStore('images').get(p.asset);q.onsuccess=()=>ok(q.result)});if(blob)state.images.set(p.asset,await loadImage(URL.createObjectURL(blob)))}}catch{}draw()}
function play(){if(song.paused){song.play().then(()=>{syncReference(true);baseline.play().catch(()=>{});if(state.view!=='edit')ref.play().catch(()=>{})}).catch(()=>tell('音源の再生を開始できませんでした'))}else{song.pause();ref.pause();baseline.pause()}$('play').textContent=song.paused?'▶ 再生':'⏸ 一時停止'}
function tick(){if(!song.paused){renderTime();draw();syncReference()}requestAnimationFrame(tick)}
function view(mode){state.view=mode;for(const b of document.querySelectorAll('.view'))b.classList.toggle('active',b.dataset.view===mode);$('stageWrap').classList.toggle('split',mode==='split');$('referenceStage').style.display=mode==='edit'?'none':'block';$('editStage').style.display=mode==='original'?'none':'block';syncReference(true);if(song.paused){ref.pause();baseline.pause()}else{baseline.play().catch(()=>{});if(mode!=='edit')ref.play().catch(()=>{});else ref.pause()}}
function pointerStage(e){if(state.view==='original'||!state.selected)return;const x=selected();if(!x)return;const before=clone(state.data),rect=canvas.getBoundingClientRect(),sx=960/rect.width,sy=540/rect.height,px=e.clientX,py=e.clientY,startX=x.x||0,startY=x.y||0,startScale=x.scale||1,resizing=state.selected.type==='lyrics'&&Math.abs((px-rect.left)*sx-960*(.88+startX))<30&&Math.abs((py-rect.top)*sy-540*(.73+startY))<30;canvas.setPointerCapture(e.pointerId);const move=ev=>{const dx=(ev.clientX-px)*sx/960,dy=(ev.clientY-py)*sy/540;if(resizing)x.scale=Math.max(.1,+(startScale+(ev.clientX-px)*sx/450).toFixed(3));else{x.x=+(startX+dx).toFixed(4);x.y=+(startY+dy).toFixed(4)}updatePlan();draw()};const up=()=>{canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);record(before)};canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up)}
function pointerClip(e){let el=e.target.closest('.clip');if(!el)return;const type=el.dataset.type,id=el.dataset.id,x=item(type,id);if(!x)return;const handle=e.target.dataset.handle;choose(type,id,false);if(!handle){setTime(Math.min(x.end-.04,x.start+.2));return}e.stopPropagation();const before=clone(state.data),px=e.clientX,origin=x[handle==='left'?'start':'end'];el.setPointerCapture(e.pointerId);const move=ev=>{const v=sec(origin+(ev.clientX-px)/state.zoom);if(handle==='left')x.start=Math.min(x.end-.01,v);else x.end=Math.max(x.start+.01,v);el.style.left=x.start*state.zoom+'px';el.style.width=Math.max(8,(x.end-x.start)*state.zoom)+'px';updatePlan();draw();inspector()};const up=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up);record(before)};el.addEventListener('pointermove',move);el.addEventListener('pointerup',up)}
function download(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function exportJSON(){download('ByeByeBLUE_v47_edits_v5.json',new Blob([JSON.stringify({version:5,base:'ByeByeBLUE_v47',data:state.data},null,2)],{type:'application/json'}))}
async function importJSON(file){try{const p=JSON.parse(await file.text());if(p.version!==5||p.base!=='ByeByeBLUE_v47'||!Array.isArray(p.data.photos)||!Array.isArray(p.data.lyrics))throw Error();const before=clone(state.data);state.data=p.data;state.selected=null;updatePlan();record(before);loadReplacements();tell('v47用の編集データを読み込みました')}catch{tell('v47用の編集データを読み込めませんでした')}}
async function recordVideo(){if(state.recording)return;const stream=canvas.captureStream(30);let ac=new AudioContext(),source=ac.createMediaElementSource(song),dest=ac.createMediaStreamDestination();source.connect(dest);source.connect(ac.destination);for(const t of dest.stream.getAudioTracks())stream.addTrack(t);if(!MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')&&!MediaRecorder.isTypeSupported('video/webm')){tell('このブラウザーではWebM記録ができません');return}let chunks=[],mr=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?'video/webm;codecs=vp9,opus':'video/webm'});mr.ondataavailable=e=>e.data.size&&chunks.push(e.data);mr.onstop=()=>{download('ByeByeBLUE_edited.webm',new Blob(chunks,{type:'video/webm'}));state.recording=false;$('record').disabled=false;tell('動画を書き出しました')};state.recording=true;$('record').disabled=true;setTime(0);view('edit');mr.start(1000);await song.play();tell('動画を記録中です。再生終了までこの画面を開いてください');song.addEventListener('ended',()=>mr.stop(),{once:true})}
function bind(){song.addEventListener('play',()=>{$('play').textContent='⏸ 一時停止'});song.addEventListener('pause',()=>{$('play').textContent='▶ 再生'});song.addEventListener('seeked',()=>{draw();syncReference(true)});$('play').onclick=play;$('seek').oninput=e=>setTime(e.target.value);$('back').onclick=()=>setTime(song.currentTime-.1);$('forward').onclick=()=>setTime(song.currentTime+.1);$('zoom').oninput=e=>{state.zoom=+e.target.value;timeline();waveform()};document.querySelectorAll('.view').forEach(b=>b.onclick=()=>view(b.dataset.view));$('screen').addEventListener('pointerdown',pointerStage);for(const id of ['photos','lyrics','effects'])$(id).addEventListener('pointerdown',pointerClip);$('ruler').onclick=e=>setTime((e.clientX-$('ruler').getBoundingClientRect().left)/state.zoom);$('wave').onclick=e=>setTime((e.clientX-$('wave').getBoundingClientRect().left)/state.zoom);$('undo').onclick=()=>{if(!state.history.length)return;state.future.push(clone(state.data));state.data=state.history.pop();updatePlan();save();refresh()};$('redo').onclick=()=>{if(!state.future.length)return;state.history.push(clone(state.data));state.data=state.future.pop();updatePlan();save();refresh()};$('resetItem').onclick=()=>{const s=state.selected,original=item(s.type,s.id,state.base);if(!original)return;const before=clone(state.data),i=state.data[s.type].findIndex(x=>x.id===s.id);state.data[s.type][i]=clone(original);updatePlan();record(before)};$('resetAll').onclick=()=>{const before=clone(state.data);state.data=clone(state.base);state.selected=null;updatePlan();record(before);tell('MV全体を元に戻しました。元に戻すボタンで取り消せます')};$('save').onclick=save;$('export').onclick=exportJSON;$('import').onclick=()=>$('importFile').click();$('importFile').onchange=e=>{if(e.target.files[0])importJSON(e.target.files[0]);e.target.value=''};$('addPhoto').onclick=()=>add('photos');$('addLyric').onclick=()=>add('lyrics');for(const [id,dir] of [['prevCue',-1],['nextCue',1]])$(id).onclick=()=>{let xs=state.data.lyrics,t=song.currentTime,found=dir>0?xs.find(x=>x.start>t+.02):xs.filter(x=>x.start<t-.02).at(-1);if(found)choose('lyrics',found.id)}}
function add(type){let before=clone(state.data),start=sec(song.currentTime),end=Math.min(DURATION,start+2),id='new-'+Date.now(),x=type==='photos'?{id,cut:null,label:'追加した写真',asset:state.data.photos[0].asset,start,end,x:0,y:0,scale:1,panAmount:0,zoomAmount:0,fadeIn:0,fadeOut:0,crossfade:0}:{id,line:undefined,text:'新しい歌詞',start,end,mode:'type',x:0,y:0,scale:1,tracking:0,lineBreak:0,lineSpacing:1,align:'center',enterEffect:'original',exitEffect:'original',rotation:0,panelSide:'off',bandWidth:null,bandHeight:null,bandAngle:null,bandPosition:0,bandMotion:null,bandStart:0,bandEnd:0,panelWidth:null,panelPosition:0,panelMotion:0};state.data[type].push(x);updatePlan();record(before);choose(type,id)}
async function init(){const [cuts,timing,project,wave]=await Promise.all(['cuts-v39.json','timing-v39.json','jizura-project.json','waveform.json'].map(f=>fetch(A+f).then(r=>r.json())));state.wave=wave;state.base={version:5,project,photos:cuts.map(c=>({id:'cut-'+c.cut,cut:c.cut,label:c.place_angle,asset:c.cut===16?'window_evening':c.source_id,start:c.start,end:c.end,x:0,y:0,scale:1,panAmount:1,zoomAmount:0,fadeIn:0,fadeOut:0,crossfade:0})),lyrics:timing.map(c=>({id:'line-'+c.line,line:c.line,text:c.text==='Bye Bye Bye'?'BYE BYE BYE':/^byebye /i.test(c.text)?c.text.replace(/^byebye/i,'ByeBye'):c.text,start:c.display_start,end:c.display_end,mode:c.text==='Bye Bye Bye'?'band':cutMode(c.line),x:0,y:0,scale:1,tracking:0,lineBreak:0,lineSpacing:1,align:'center',enterEffect:'original',exitEffect:'original',rotation:0,panelSide:'',bandWidth:null,bandHeight:null,bandAngle:null,bandPosition:0,bandMotion:null,bandStart:0,bandEnd:0,panelWidth:null,panelPosition:0,panelMotion:0}))};
 try{let saved=JSON.parse(localStorage.getItem('bye-bye-blue-v5'));state.data=saved?.version===5&&saved.photos?.length? saved:clone(state.base)}catch{state.data=clone(state.base)}
 J.fontCSS=(font,px)=>`700 ${px.toFixed(2)}px IPAexG`;await document.fonts.load('700 80px IPAexG');state.renderer=new J.Renderer();updatePlan();bind();refresh();waveform();view('edit');requestAnimationFrame(tick);const names=[...new Set(state.base.photos.map(x=>x.asset))];await Promise.all(names.map(async n=>{try{state.images.set(n,await loadImage(A+'photos/'+n+'.webp'));draw()}catch{console.warn('missing photo',n)}}));loadReplacements();tell('v47の54カット・85歌詞を読み込みました')}
init().catch(e=>{console.error(e);tell('素材を読み込めませんでした。ページを再読み込みしてください')});
})();
