import {getAccessUserId} from '../../access-auth';
import {database} from '@/db/raw';
import {GRADES,text,year,scores,averageValues} from '@/lib/score';
export const dynamic='force-dynamic';
class ApiError extends Error {constructor(message:string,public status=400){super(message)}}
function fail(error:unknown){console.error('Score Input',error);const message=error instanceof Error?error.message:'処理に失敗しました';return Response.json({error:message.includes('UNIQUE constraint')?'同じ登録がすでにあります。登録内容を確認してください。':error instanceof ApiError||!/D1|SQLITE|constraint|binding/i.test(message)?message:'保存先への接続に失敗しました。入力内容を残して再度お試しください。'},{status:error instanceof ApiError?error.status:400,headers:{'Cache-Control':'no-store'}})}
async function user(){const id=await getAccessUserId();if(!id)throw new ApiError('ログインしてから利用してください',401);return id;}
async function campus(db:D1Database,id:string,owner:string){const c=await db.prepare('SELECT id,name FROM campuses WHERE id=? AND owner=?').bind(id,owner).first();if(!c)throw new ApiError('この校舎を利用できません',403);return c;}
function grade(v:unknown){const g=text(v,'学年');if(!GRADES.includes(g))throw new ApiError('学年を選択してください');return g;}
async function test(db:D1Database,id:string,c:string){const t=await db.prepare('SELECT * FROM tests WHERE id=? AND campus_id=?').bind(id,c).first();if(!t)throw new ApiError('この校舎のテストを選択してください');return t;}
export async function GET(req:Request){try{const owner=await user(),db=database();const campuses=(await db.prepare('SELECT id,name FROM campuses WHERE owner=? ORDER BY created_at').bind(owner).all()).results;const id=new URL(req.url).searchParams.get('campus');if(!id)return Response.json({campuses,students:[],tests:[],records:[],averages:[]},{headers:{'Cache-Control':'no-store'}});await campus(db,id,owner);const [students,tests,records,averages]=await db.batch<Record<string,unknown>>([db.prepare('SELECT * FROM students WHERE campus_id=? ORDER BY name').bind(id),db.prepare('SELECT * FROM tests WHERE campus_id=? ORDER BY year DESC,sort_order,name').bind(id),db.prepare('SELECT * FROM records WHERE campus_id=? ORDER BY updated_at DESC').bind(id),db.prepare('SELECT * FROM averages WHERE campus_id=?').bind(id)]);return Response.json({campuses,students:students.results,tests:tests.results,records:records.results.map(r=>({...r,scores:JSON.parse(String(r.scores_json)),averages:JSON.parse(String(r.averages_json))})),averages:averages.results.map(r=>({...r,values:JSON.parse(String(r.values_json))}))},{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new ApiError('別のサイトからの保存は受け付けられません',403);const owner=await user(),db=database();if(Number(req.headers.get('content-length')||0)>20000)throw new ApiError('入力内容が大きすぎます');const body=await req.text();if(body.length>20000)throw new ApiError('入力内容が大きすぎます');const d=JSON.parse(body);if(!d||typeof d!=='object'||Array.isArray(d))throw new ApiError('入力内容を確認してください');const action=d.action;const stamp=new Date().toISOString();
if(action==='createCampus'){const id=crypto.randomUUID(),name=text(d.name,'校舎名');await db.prepare('INSERT INTO campuses(id,owner,name,created_at) VALUES(?,?,?,?)').bind(id,owner,name,stamp).run();return Response.json({ok:true,id});}
const id=text(d.campusId,'校舎');await campus(db,id,owner);
if(action==='renameCampus'){await db.prepare('UPDATE campuses SET name=? WHERE id=? AND owner=?').bind(text(d.name,'校舎名'),id,owner).run();}
else if(action==='saveStudent'){const name=text(d.name,'生徒名'),g=grade(d.grade),school=text(d.school,'学校名'),code=text(d.code,'生徒番号'),start=year(d.startYear),status=d.status==='退塾'?'退塾':'在籍';if(d.id){const r=await db.prepare('UPDATE students SET name=?,grade=?,school=?,code=?,start_year=?,status=? WHERE id=? AND campus_id=?').bind(name,g,school,code,start,status,text(d.id,'生徒'),id).run();if(!r.meta.changes)throw new ApiError('生徒が見つかりません');}else await db.prepare('INSERT INTO students(id,campus_id,code,name,grade,school,status,start_year) VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,code,name,g,school,status,start).run();}
else if(action==='saveTest'){const name=text(d.name,'テスト名'),y=year(d.year);await db.prepare('INSERT INTO tests(id,campus_id,year,name,sort_order) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,y,name,Date.now()).run();}
else if(action==='saveAverage'){const tid=text(d.testId,'テスト');await test(db,tid,id);const g=grade(d.grade),school=text(d.school,'学校名'),values=averageValues(d.values);await db.prepare('INSERT INTO averages(id,campus_id,test_id,grade,school,values_json) VALUES(?,?,?,?,?,?) ON CONFLICT(campus_id,test_id,grade,school) DO UPDATE SET values_json=excluded.values_json').bind(crypto.randomUUID(),id,tid,g,school,JSON.stringify(values)).run();}
else if(action==='saveRecord'){const sid=text(d.studentId,'生徒'),tid=text(d.testId,'テスト'),t=await test(db,tid,id);const st=await db.prepare('SELECT * FROM students WHERE id=? AND campus_id=?').bind(sid,id).first();if(!st||st.status!=='在籍'||Number(st.start_year)>Number(t.year))throw new ApiError('対象年度に入力できる在籍生徒を選択してください');const revision=Number(d.revision);if(!Number.isInteger(revision)||revision<0)throw new ApiError('保存内容を再読み込みしてください');const vals=scores(d.scores),rank=d.rank===''||d.rank==null?null:Number(d.rank);if(rank!==null&&(!Number.isInteger(rank)||rank<1))throw new ApiError('順位は1以上の整数で入力してください');const memo=typeof d.memo==='string'?d.memo:'';if(memo.length>2000)throw new ApiError('メモは2000文字以内にしてください');const a=await db.prepare('SELECT values_json FROM averages WHERE campus_id=? AND test_id=? AND grade=? AND school=?').bind(id,tid,st.grade,st.school).first();const avg=String(a?.values_json||'{}'),collect=d.collect==='回収済'?'回収済':'未回収';const values=[String(st.grade),String(st.school),JSON.stringify(vals),avg,rank,collect,memo,stamp];let result;if(revision===0){result=await db.prepare('INSERT INTO records(id,campus_id,student_id,test_id,grade,school,scores_json,averages_json,rank,collect,memo,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(campus_id,student_id,test_id) DO NOTHING').bind(crypto.randomUUID(),id,sid,tid,...values).run();}else{result=await db.prepare('UPDATE records SET grade=?,school=?,scores_json=?,averages_json=?,rank=?,collect=?,memo=?,updated_at=?,revision=revision+1 WHERE campus_id=? AND student_id=? AND test_id=? AND revision=?').bind(...values,id,sid,tid,revision).run();}if(!result.meta.changes)throw new ApiError('他の画面で成績が変更されています。再読み込みして確認してください。',409);}
else if(action==='deleteRecord'){const revision=Number(d.revision);if(!Number.isInteger(revision)||revision<1)throw new ApiError('保存済み成績を選択してください');const result=await db.prepare('DELETE FROM records WHERE campus_id=? AND student_id=? AND test_id=? AND revision=?').bind(id,text(d.studentId,'生徒'),text(d.testId,'テスト'),revision).run();if(!result.meta.changes)throw new ApiError('成績が変更されているか、削除されています。再読み込みしてください。',409);}
else throw new ApiError('未対応の操作です');return Response.json({ok:true});
}catch(e){return fail(e)}}
